/**
 * The slidx task graph.
 *
 * Vite+ is the task runner for the whole repository — Rust and TypeScript
 * alike. Cargo and `vp` both know how to cache their own work, but neither
 * knows about the other, so the dependency edges between them live here. That
 * is what makes `vp run workspace:ci` reproduce CI exactly, rather than
 * approximating it with a list of commands that drift apart.
 *
 * Task names follow `<verb>:<subject>`. The `workspace:*` tasks are the ones a
 * person types; everything else is a node in the graph.
 */

import { spawnSync } from "node:child_process";

import { defineConfig } from "vite-plus";

/**
 * Vite+'s own `build`, `check`, `fmt`, and `test` commands bypass `run.tasks`,
 * so typing `vp check` at the root would run only the TypeScript half and
 * silently skip Rust. Delegating the bare commands into the task graph makes
 * the short form and the long form mean the same thing.
 *
 * The environment variable breaks the recursion: tasks that genuinely want the
 * built-in wrap their command in `builtin()`.
 */
const LIFECYCLE_ENV = "SLIDX_VP_LIFECYCLE";

const LIFECYCLE_TASKS: Record<string, string> = {
  build: "workspace:build",
  check: "workspace:check",
  fmt: "workspace:fmt",
  lint: "workspace:lint",
  test: "workspace:test",
};

function delegateLifecycleCommand(): void {
  if (process.env[LIFECYCLE_ENV]) return;

  const [, , command, ...args] = process.argv;
  const taskName = command ? LIFECYCLE_TASKS[command] : undefined;

  // Only the bare form delegates. `vp test some/path` is a deliberate
  // narrowing and should reach the built-in unchanged.
  if (!taskName || args.length > 0) return;

  const result = spawnSync("vp", ["run", taskName], {
    env: { ...process.env, [LIFECYCLE_ENV]: "1" },
    stdio: "inherit",
  });

  if (result.error) throw result.error;
  process.exit(result.status ?? 1);
}

delegateLifecycleCommand();

interface TaskOptions {
  cwd?: string;
  dependsOn?: string[];
  cache?: false;
}

const task = (command: string, options: TaskOptions = {}) => ({ command, ...options });

/** A task that exists only to group others. */
const group = (dependsOn: string[], options: TaskOptions = {}) =>
  task('node -e ""', { dependsOn, ...options });

/** A task whose output is not worth caching, or is not a pure function of the tree. */
const uncached = (command: string, options: Omit<TaskOptions, "cache"> = {}) =>
  task(command, { ...options, cache: false });

/** Reaches Vite+'s built-in command instead of re-entering the task graph. */
const builtin = (command: string) => `${LIFECYCLE_ENV}=1 ${command}`;

export default defineConfig({
  fmt: {
    // `assets/brand/**` is generated by `slidx_brand`, which is the opposite
    // choice from `deck.d.ts` and for a reason. That file is the boundary
    // TypeScript consumers read, so the formatter has the last word on it and
    // the drift check normalises whitespace away. These are machine output that
    // nobody edits, so the generator owns their layout and the check can be
    // byte-exact — which is the stronger of the two.
    ignorePatterns: ["**/target/**", "**/dist/**", "assets/brand/**"],
  },

  lint: {
    options: {
      typeAware: true,
    },
  },

  test: {
    // The runtime package manipulates real DOM nodes: the anchor contract is
    // about where an element ends up in a tree, which cannot be asserted
    // against a mock.
    environment: "happy-dom",
    passWithNoTests: true,
    // Parallel work happens in scratch worktrees under `.claude/`, which are
    // whole checkouts of this repository. Without this the suite runs every
    // test once per worktree, against code that is deliberately not merged.
    exclude: ["**/node_modules/**", "**/dist/**", ".claude/**"],
  },

  run: {
    cache: {
      scripts: true,
      tasks: true,
    },

    tasks: {
      // What to type before pushing. Runs everything CI runs.
      "workspace:ci": group(["ci:conventions", "ci:rust", "ci:ts", "ci:build"]),

      // CI schedules these one per job, so a failure names the area rather
      // than the repository. They are still nodes in this graph rather than
      // steps in a workflow file — a check that exists here cannot go missing
      // from CI, because CI has no steps of its own to forget.
      "ci:conventions": group([
        "check:conventions",
        "check:version",
        "check:borrowed",
        "check:dead-config",
        "check:flat",
        "check:licensed",
      ]),
      "ci:rust": group([
        "fmt:rust-check",
        "lint:rust",
        "test:rust",
        "check:deck-fmt",
        "check:deck-lint",
      ]),
      "ci:ts": group(["fmt:ts-check", "check:ts", "check:types", "test:ts"]),
      "ci:build": group(["build:rust", "build:packages", "check:packages-built"]),

      "workspace:check": group([
        "check:conventions",
        "check:borrowed",
        "check:dead-config",
        "check:flat",
        "check:licensed",
        "check:version",
        "fmt:rust-check",
        "fmt:ts-check",
        "lint:rust",
        "check:deck-fmt",
        "check:deck-lint",
        "check:ts",
        "check:types",
      ]),
      "workspace:test": group(["test:rust", "test:ts"]),
      "workspace:build": group(["build:rust", "build:packages"]),
      "workspace:fmt": group(["fmt:rust", "fmt:ts"]),
      "workspace:lint": group(["lint:rust", "check:ts"]),

      // Rust.
      //
      // Everything that compiles is `uncached`. Cargo already has a good
      // incremental cache and it lives in `target/`, inside the workspace, so
      // Vite+ sees each of these tasks read and write its own inputs and
      // declines to cache them anyway. Saying so explicitly is honest — it
      // keeps the run summary free of "not cached" noise that looks like a
      // problem, and it makes clear that cargo owns Rust incrementality.
      //
      // `fmt:rust` is the exception: it touches nothing under `target/`, so it
      // caches like any other task.
      //
      // `check:rust` runs before clippy so a type error is reported as a type
      // error rather than buried in lint output.
      "check:rust": uncached("cargo check --workspace --all-targets"),
      "lint:rust": uncached("cargo clippy --workspace --all-targets -- -D warnings", {
        dependsOn: ["check:rust"],
      }),
      "fmt:rust": task("cargo fmt --all"),
      "fmt:rust-check": task("cargo fmt --all -- --check"),
      "test:rust": uncached("cargo test --workspace"),

      // slidx's own example deck, held to slidx's own formatter.
      //
      // The deck in `examples/deck` is what the README screenshots come from and
      // the only deck in the repository a reader will copy, so a dialect it
      // spells three different ways is a worked example of the wrong thing.
      // `--check` writes nothing, so a failure here is fixed by running
      // `slidx fmt examples/deck/slides` and reading the diff.
      //
      // Grouped with the Rust tasks rather than with the convention checks
      // because it runs the binary: it takes cargo's lock on `target/`, and a
      // task that blocks on a lock belongs beside the ones holding it.
      "check:deck-fmt": uncached(
        "cargo run -q -p slidx_cli --bin slidx -- fmt examples/deck/slides --check",
        { dependsOn: ["check:rust"] },
      ),

      // And to slidx's own rules, which is the half a formatter cannot see.
      //
      // Both halves of what `slidx lint` reports: what a room does to a slide,
      // and whether the deck asks for something that will happen. An example
      // deck naming a theme or a step target that does not exist teaches
      // whoever copies it to do the same.
      "check:deck-lint": uncached(
        "cargo run -q -p slidx_cli --bin slidx -- lint examples/deck/slides",
        { dependsOn: ["check:rust"] },
      ),
      // The Zed extension, which is a workspace of its own and a target no
      // other task uses. Compiling it is the whole check there is: Zed builds
      // it the same way, and nothing else in this repository links it, so
      // without this a change to its forty lines of glue would be found by
      // whoever next tried to install it.
      //
      // Not in `ci:rust` — that job runs on three platforms and this needs
      // `wasm32-wasip2` on each of them to prove something that is true once.
      // CI gives it a runner of its own; see `.github/workflows/ci.yml`.
      "build:zed": uncached(
        "cargo build --release --locked --target wasm32-wasip2 --manifest-path editors/zed/Cargo.toml",
      ),

      "test:rust-verbose": uncached("cargo test --workspace -- --nocapture"),
      "build:rust": uncached("cargo build --workspace --release"),
      "doc:rust": uncached("cargo doc --workspace --no-deps"),

      // The wasm package is the boundary every JavaScript consumer goes
      // through, so nothing on that side can be checked until it exists.
      "build:wasm": uncached("node scripts/build-wasm.mjs"),

      // The TypeScript form of the deck and of publishing, written out of the
      // Rust types.
      //
      // Nothing depends on this task, and that is the point. The generated
      // files are committed, so `build:wasm` finds them already there and a
      // change to the boundary arrives in review as a diff rather than as a
      // rebuild nobody sees. What keeps them honest is `test:rust`, which CI
      // already runs and which fails the moment a file stops describing the
      // types it came from. This task is how you fix that failure.
      "generate:types": uncached(
        "vp fmt crates/slidx_wasm/deck.d.ts crates/slidx_wasm/publish.d.ts",
        { dependsOn: ["generate:types-raw"] },
      ),

      // Two tasks because two tools have opinions: the generator writes
      // `ts-rs`'s spelling, and the repository's formatter has the last word
      // on how a file someone has to read is laid out.
      "generate:types-raw": uncached(
        "SLIDX_WRITE_DECK_TYPES=1 cargo test -p slidx_wasm --lib the_committed_",
      ),

      // The token document `@slidxjs/theme-workshop` publishes. Committed for the
      // reason every generated file here is: the package ships to npm and its
      // consumers cannot call Rust. `test:rust` fails when the committed copy
      // stops describing `slidx_theme::published`, and this task is how you fix
      // that failure — a theme package's palette is the one thing that must not
      // be a list of hexes somebody pasted.
      "generate:theme": uncached("cargo run -p slidx_theme --example pack"),

      // Every file under `assets/brand/` — the mark, the wordmark, the tokens.
      // Committed for the same reason the deck types are: their consumers, the
      // documentation site and the icon script, cannot call Rust. `test:rust`
      // fails when a committed copy stops describing the crate, and this task is
      // how you fix that failure.
      "generate:brand": uncached("cargo run -p slidx_brand --example emit"),

      // The runtime is consumed through its published `exports`, which point
      // at `dist/`. Importing it from source instead would test a module that
      // no user ever loads, so it is built before anything reads it. This is
      // the edge CI caught and a local tree hides: `dist/` is gitignored and
      // is already there on a machine that has run a build once.
      "build:runtime": uncached("vp run --filter @slidxjs/runtime pack:lib"),

      // The editor is read off disk by the dev server the same way, and for
      // the same reason: it is served as a module, not imported as one.
      //
      // It has to be *one* module: the dev server hands the file to a browser
      // as-is, so a bare import left in it would fail to resolve at runtime.
      // The editor's timeline reuses the runtime's mirror and its stop cursor,
      // and that import resolves through `exports` — which points at `dist/`,
      // so the runtime has to exist before the editor is packed or it silently
      // stays external.
      "build:editor": uncached("vp run --filter @slidxjs/editor pack:lib", {
        dependsOn: ["build:runtime"],
      }),

      // The plugin is consumed through its `exports` too — `examples/deck`
      // imports `@slidxjs/vite-plugin`, and so does anything running a real
      // build. Nothing built it, and the two ways that failed are worth naming
      // because only one of them looks like a failure.
      //
      // On a clean checkout there is no `dist/` and the example deck cannot run
      // at all, which at least says so. On a machine that built it once, a
      // *stale* `dist/` answers instead: a check runs, passes, and reports on
      // code from whenever that build happened. Verifying a security boundary
      // against a stale plugin is how one was found unenforced that was not.
      //
      // Only the wasm types are needed to emit the declarations; the runtime
      // and the editor are read off disk at run time, not imported.
      "build:plugin": uncached("vp run --filter @slidxjs/vite-plugin pack:lib", {
        dependsOn: ["build:wasm"],
      }),

      // The VS Code extension. It is `private`, so it is never published and
      // `check:packages-built` does not cover it — and an extension nobody
      // builds is an extension nobody can install, which is the exact shape of
      // the problem this whole editor item exists to end. So it is built here,
      // where a failure to compile is a failure of the build rather than a
      // surprise at packaging time.
      //
      // CommonJS because that is what an extension host loads, in a package
      // that is `"type": "module"` like every other one here.
      "build:vscode": uncached("vp run --filter slidx-vscode pack:lib"),

      // The four nothing in this repository imports. They are published all the
      // same, and each declares `files: ["dist"]`, so leaving them unbuilt does
      // not fail anything here — it publishes a tarball holding one
      // `package.json` and calls it a package.
      "build:audience": uncached("vp run --filter @slidxjs/audience pack:lib"),
      "build:islands": uncached("vp run --filter @slidxjs/islands pack:lib"),
      "build:rehearsal": uncached("vp run --filter @slidxjs/rehearsal pack:lib"),
      "build:publish": uncached("vp run --filter @slidxjs/publish pack:lib", {
        dependsOn: ["build:wasm"],
      }),

      "build:packages": group([
        "build:wasm",
        "build:runtime",
        "build:editor",
        "build:plugin",
        "build:vscode",
        "build:audience",
        "build:islands",
        "build:rehearsal",
        "build:publish",
      ]),

      // Asks the filesystem rather than reading the task graph, because the
      // graph cannot answer it: `build:wasm` runs a script and never names the
      // package it produces. Depends on the build for the same reason — the
      // question is whether a build leaves every imported package loadable.
      "check:packages-built": uncached("node scripts/check-packages-built.mjs", {
        dependsOn: ["build:packages"],
      }),

      // TypeScript.
      "check:ts": task(builtin("vp check"), { dependsOn: ["build:packages"] }),

      // `vp check` runs the formatter and a type-aware linter, which is not
      // the same thing as a type check: it reads types to answer lint
      // questions and never asks whether the program type-checks. Nothing did,
      // so `tsconfig.json` had `exactOptionalPropertyTypes` and
      // `noUncheckedIndexedAccess` switched on and a tree that did not pass
      // either — including a reference to a name that was never imported.
      //
      // Depends on the built packages: `@slidxjs/wasm` is where the deck type
      // lives, and it is generated rather than committed to a source folder.
      "check:types": task("tsc --noEmit -p tsconfig.json", { dependsOn: ["build:packages"] }),
      "fmt:ts": task(builtin("vp fmt")),
      "fmt:ts-check": task(builtin("vp fmt --check")),

      // Uncached for a mechanical reason rather than a principled one: loading
      // this TypeScript config writes a transpiled copy into
      // `node_modules/.vite-temp`, which reads as the task modifying its own
      // input. Marking it explicitly keeps the run summary honest instead of
      // reporting a miss on every run.
      "test:ts": uncached(builtin("vp test"), { dependsOn: ["build:packages"] }),

      // Cutting a release. `vp run release minor` writes the version everywhere
      // it lives, runs `check:version` against the tag it is about to create,
      // and pushes that tag — which starts a publish nobody can take back.
      // Uncached for the obvious reason: it is not a function of the tree.
      release: uncached("node scripts/release.mjs"),

      "check:conventions": task("node scripts/check-conventions.mjs"),
      "check:dead-config": task("node scripts/check-dead-config.mjs"),

      // No shadows, no gradients, anywhere slidx draws. A gate rather than a
      // warning: the size guideline is a judgement call about how much a file is
      // holding, and this one is not.
      "check:flat": task("node scripts/check-flat.mjs"),

      // The MIT notice beside every manifest that becomes a tarball. Neither
      // cargo nor npm looks outside a package directory for one, so the copy at
      // the root of this workspace reaches none of the 28 things it licenses —
      // which a publish dry run found, and which is much easier to fix before
      // a version exists than after.
      "check:licensed": task("node scripts/check-licensed.mjs"),

      // No palette pasted from a framework, and no palette written as hex
      // literals at all. slidx shipped one popular framework's `zinc` ramp for
      // months without anyone noticing, because a pasted palette looks exactly
      // like a chosen one once it is in a file.
      "check:borrowed": task("node scripts/check-borrowed.mjs"),
      "check:version": task("node scripts/check-version.mjs"),

      // The documentation site. Nothing depends on this and CI does not run
      // it, because building is not what keeps the site honest: `test:rust`
      // reads the real pages, renders every one, and fails on a dead link or a
      // page in a section that does not exist. This task is for looking at the
      // result — the pages are self-contained, so opening `docs/dist/index.html`
      // needs no server.
      "docs:build": uncached("cargo run -p slidx_docs --example build"),

      // The README images are output of the pipeline, not artwork. Kept as a
      // task so regenerating them is one command and never a manual crop.
      //
      // Depends on the plugin, which the example deck imports through its
      // `exports`. Without that edge, regenerating the images on a clean
      // checkout fails inside esbuild with "Failed to resolve entry for package
      // @slidxjs/vite-plugin" — a message about a bundler, for a missing build.
      "preview:deck": uncached("vp exec --filter slidx-example-deck -- vite build", {
        // A production deck resolves these through their published `exports`.
        // A warm checkout hides a missing edge with old `dist/` directories;
        // media generation must also work from a clean clone.
        dependsOn: ["build:plugin", "build:runtime", "build:rehearsal", "build:islands"],
      }),
      screenshots: uncached("node scripts/screenshot.mjs", { dependsOn: ["preview:deck"] }),

      // Every picture and recording the documentation site uses, from real
      // runs: `slidx` under a pty so its own colour survives, and the built
      // deck driven by the arrow key a remote sends. Needs the built deck for
      // the same reason the screenshots do.
      media: uncached("node scripts/record.mjs", { dependsOn: ["preview:deck"] }),

      // The editor's gestures, recorded by performing them against a real dev
      // server. Everything the README and the documentation site claim about
      // direct manipulation is a picture from this task.
      //
      // Two edges, and neither is the built deck: this starts a dev server
      // rather than reading `dist/`. The plugin is what the script imports, and
      // the editor is the module that server hands to the browser — read off
      // disk through `exports`, so an editor nothing built is a page that mounts
      // nothing and a recording of an empty frame. `preview:deck` needed
      // `build:plugin` for the same class of reason.
      "record:editor": uncached("node scripts/record-editor.mjs", {
        dependsOn: ["build:plugin", "build:editor"],
      }),
      "record:tour": uncached("node scripts/record-editor-tour.mjs", {
        dependsOn: ["build:plugin", "build:editor"],
      }),

      // Benchmarks measure wall-clock time, so a cached result is a wrong one.
      "bench:rust": uncached("cargo bench --workspace"),

      // Backs the build-time and output-size figures in the README. Run it
      // before changing anything in the pipeline you expect to be free.
      "bench:build": uncached("node scripts/bench-build.mjs", {
        dependsOn: ["build:packages"],
      }),
    },
  },
});
