//! The operations that stage a slide.
//!
//! Five tools over the `steps:` list. The interesting part is the schema rather
//! than the code: a step is a *snapshot*, and the vocabulary an agent is offered
//! has to make that hard to misread. So the effect presets are enumerated from
//! the Rust enum rather than restated as a list here, and the description says
//! what each action kind is for and which gesture is not one of them.

use serde_json::{json, Value};

use slidx_core::EffectPreset;
use slidx_edit::EditOp;

use super::apply::operate;
use super::args;
use super::slide::{schema, slide_argument};
use super::{Context, Tool};
use crate::mcp::content::Answer;

pub const ALL: &[Tool] = &[
    Tool {
        name: "add_step",
        title: "Stage part of a slide",
        description: "\
Adds one intent to a slide's `steps:` list, creating it if there is none. Appends \
unless `at` says where. Each intent costs the speaker one advance.

Steps are SNAPSHOTS, not deltas: slidx compiles the list into a vector of complete \
states, so advancing, going back, deep-linking to `?step=7` and printing all index \
into the same vector and cannot drift. Describe what a stop looks like, never what \
to do on a click.

  reveal     content that is not on screen yet
  hide       content that has been and is now gone
  emphasize  content already on screen, drawn attention to
  set        content already on screen, changed in place
  group      several of the above landing on one advance

A value that CHANGES is usually none of these: write two takes of one mark instead \
— `[120ms]{#latency}[38ms]{#latency}` — and slidx compiles one element with \
successive states. Reach for `set` when a PROPERTY changes rather than the text.

Anything targeted needs a mark with that key first; `add_mark` makes one.",
        schema: add_schema,
        output: super::apply::output,
        writes: true,
        run: add_step,
    },
    Tool {
        name: "remove_step",
        title: "Take a stop out of a slide",
        description: "\
Removes one intent from a slide's `steps:` list by position. Every later step \
moves up, so removing several means working backwards or re-reading the list \
between calls.

An element whose only mention was the removed step goes back to being part of the \
slide from the start, which is what it was before anybody staged it.",
        schema: remove_schema,
        output: super::apply::output,
        writes: true,
        run: remove_step,
    },
    Tool {
        name: "set_step",
        title: "Change what one stop does",
        description: "\
Replaces one intent of a slide's `steps:` list, leaving every other stop alone. \
This is how a stop is retimed or repointed without rewriting the list.

Only works on a step that has a line in the file. Stops generated by `autoSteps:` \
or by `<!-- step -->` markers have none, so there is nothing to replace — \
`adopt_steps` writes them out first.",
        schema: set_step_schema,
        output: super::apply::output,
        writes: true,
        run: set_step,
    },
    Tool {
        name: "move_step",
        title: "Reorder a slide's stops",
        description: "\
Moves one intent of a slide's `steps:` list to a new position, counted AFTER it \
is lifted out — the same rule as moving a slide. Changes the order the speaker \
advances through, and nothing else about the slide.",
        schema: move_step_schema,
        output: super::apply::output,
        writes: true,
        run: move_step,
    },
    Tool {
        name: "adopt_steps",
        title: "Write out the stops a slide is already running",
        description: "\
Turns the stops generated by `autoSteps:` or by `<!-- step -->` markers into an \
explicit `steps:` list that says what the slide already does.

Reach for this before `set_step` or `move_step` on a slide with no written list: \
a generated stop has no line in the file, so nothing can change one in place.

There is no going back to the generated form, which is why it is its own \
operation rather than something the step tools do quietly. `autoSteps:` is left \
where it is — it is what puts the anchors the written steps name into the markup, \
so removing it would leave a list targeting nothing.",
        schema: adopt_schema,
        output: super::apply::output,
        writes: true,
        run: adopt_steps,
    },
];

fn add_schema() -> Value {
    schema(
        json!({
            "slide": slide_argument(),
            "action": {
                "type": "string",
                "enum": ["reveal", "hide", "emphasize", "set", "group"],
                "description": "What happens at this stop.",
            },
            "target": {
                "type": "string",
                "description": "\
        What the step acts on: a mark's key as `#latency`, or a CSS selector into the \
        slide. Required for everything except a group.",
            },
            "content": {
                "type": "string",
                "description": "For `set`: the element's new text.",
            },
            "properties": {
                "type": "object",
                "additionalProperties": { "type": "string" },
                "description": "For `set`: data properties to write on the element.",
            },
            "actions": {
                "type": "array",
                "items": { "type": "object" },
                "description": "\
        For `group`: the intents that land on the same advance, each shaped like this \
        object.",
            },
            "preset": {
                "type": "string",
                "enum": presets(),
                "description": "\
        The animation. Left out, slidx picks the one that suits the action, and nothing \
        is written into the deck — an editor that spells out every key turns a one-word \
        change into a diff across the whole slide.",
            },
            "durationMs": {
                "type": "integer",
                "minimum": 0,
                "description": "How long the animation runs. Default 400.",
            },
            "at": {
                "type": "integer",
                "minimum": 0,
                "description": "\
        Where in the list the intent goes, counting from zero. Left out, it is appended, \
        which is almost always what a new stop wants.",
            },
            "afterMs": {
                "type": "integer",
                "minimum": 0,
                "description": "\
        Play this many milliseconds after the stop it belongs to, INSTEAD of consuming an \
        advance of its own. This is how two things happen on one click without a group.",
            },
        }),
        &["slide", "action"],
    )
}

/// Every preset, read from the Rust enum that defines them.
///
/// Not restated as a list. A preset added to `slidx_core` has to appear here
/// without anybody remembering to add it, or the vocabulary an agent is offered
/// is a stale copy of slidx's own.
fn presets() -> Vec<&'static str> {
    EffectPreset::ALL.iter().map(|preset| preset.as_token()).collect()
}

fn add_step(context: &mut Context<'_>, arguments: &Value) -> Result<Answer, String> {
    operate(context, "add_step", arguments, |_| {
        Ok(EditOp::AddStep {
            slide: args::slide(arguments)?,
            at: args::number(arguments, "at"),
            action: args::action(arguments)?,
        })
    })
}

fn remove_schema() -> Value {
    schema(
        json!({
            "slide": slide_argument(),
            "index": {
                "type": "integer",
                "minimum": 0,
                "description": "Which step, counting from zero in the order they were written.",
            },
        }),
        &["slide", "index"],
    )
}

fn remove_step(context: &mut Context<'_>, arguments: &Value) -> Result<Answer, String> {
    operate(context, "remove_step", arguments, |_| {
        Ok(EditOp::RemoveStep {
            slide: args::slide(arguments)?,
            index: args::number(arguments, "index").ok_or_else(|| {
                "`index` is required: which step, counting from zero.".to_string()
            })?,
        })
    })
}

/// The same vocabulary `add_step` offers, plus which stop is being replaced.
///
/// Built from it rather than beside it, so a preset or an option added there
/// reaches this one without anybody remembering.
fn set_step_schema() -> Value {
    let mut extra = add_schema()["properties"].clone();
    extra["index"] = json!({
        "type": "integer",
        "minimum": 0,
        "description": "Which step to replace, counting from zero.",
    });

    schema(extra, &["slide", "index", "action"])
}

fn set_step(context: &mut Context<'_>, arguments: &Value) -> Result<Answer, String> {
    operate(context, "set_step", arguments, |_| {
        Ok(EditOp::SetStep {
            slide: args::slide(arguments)?,
            index: args::number(arguments, "index")
                .ok_or_else(|| "`index` is required: which step to replace.".to_string())?,
            action: args::action(arguments)?,
        })
    })
}

fn move_step_schema() -> Value {
    schema(
        json!({
            "slide": slide_argument(),
            "from": {
                "type": "integer",
                "minimum": 0,
                "description": "Which step to move, counting from zero.",
            },
            "to": {
                "type": "integer",
                "minimum": 0,
                "description": "\
        Its new position, counted AFTER the step is lifted out — the same rule as moving \
        a slide.",
            },
        }),
        &["slide", "from", "to"],
    )
}

fn move_step(context: &mut Context<'_>, arguments: &Value) -> Result<Answer, String> {
    operate(context, "move_step", arguments, |_| {
        Ok(EditOp::MoveStep {
            slide: args::slide(arguments)?,
            from: args::number(arguments, "from")
                .ok_or_else(|| "`from` is required: which step to move.".to_string())?,
            to: args::number(arguments, "to")
                .ok_or_else(|| "`to` is required: the step's new position.".to_string())?,
        })
    })
}

fn adopt_schema() -> Value {
    schema(json!({ "slide": slide_argument() }), &["slide"])
}

fn adopt_steps(context: &mut Context<'_>, arguments: &Value) -> Result<Answer, String> {
    operate(context, "adopt_steps", arguments, |_| {
        Ok(EditOp::AdoptSteps { slide: args::slide(arguments)? })
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_presets_offered_are_the_ones_slidx_has() {
        // Read from the enum, so a preset added in slidx_core cannot be missing
        // here and a preset removed cannot be offered.
        let offered = add_schema()["properties"]["preset"]["enum"].clone();

        assert_eq!(offered.as_array().expect("presets").len(), EffectPreset::ALL.len());
        assert!(offered.as_array().expect("presets").contains(&json!("fly-in")));
    }

    #[test]
    fn the_snapshot_rule_is_stated_where_a_step_is_written() {
        assert!(ALL[0].description.contains("SNAPSHOTS, not deltas"));
        assert!(ALL[0].description.contains("never what"), "{}", ALL[0].description);
    }

    #[test]
    fn each_action_kind_says_what_it_is_for() {
        for kind in ["reveal", "hide", "emphasize", "set", "group"] {
            assert!(ALL[0].description.contains(kind), "add_step never mentions {kind}");
        }
    }

    #[test]
    fn the_take_alternative_is_offered_beside_the_actions_it_is_mistaken_for() {
        // The failure: reaching for hide-and-reveal when the gesture is a value
        // that changes.
        assert!(ALL[0].description.contains("[120ms]{#latency}[38ms]{#latency}"));
    }

    #[test]
    fn removing_a_step_warns_that_the_later_ones_move() {
        // Removing steps 1 and 2 by index in that order removes 1 and 3.
        assert!(ALL[1].description.contains("moves up"), "{}", ALL[1].description);
    }

    #[test]
    fn playing_after_a_stop_is_documented_as_the_alternative_to_a_group() {
        let schema = add_schema();
        let after = schema["properties"]["afterMs"]["description"].as_str().expect("a text");

        assert!(after.contains("INSTEAD of consuming an advance"), "{after}");
    }
}
