//! The function that lets slidx move the directory you are standing in.
//!
//! A process cannot change its parent's working directory. That is not a gap in
//! any operating system's API, it is what a process *is* — so a command that
//! finds a deck can only print where the deck is, and the shell that ran it is
//! the only thing that can go there.
//!
//! So slidx ships a function rather than pretending. It runs the binary, prints
//! what the binary printed, and follows it when what came back was a directory.
//!
//! ## Which commands it captures, and why not all of them
//!
//! Only the ones [`crate::command`] marks — see
//! [`Command::takes_the_caller_with_it`](crate::command::Command::takes_the_caller_with_it).
//! Everything else is passed straight through.
//!
//! That is a correctness requirement, not a shortcut. Capturing a command's
//! standard output makes it a pipe: colour switches itself off, and the whole
//! report arrives at once when the command finishes rather than as it runs. A
//! wrapper that captured `slidx doctor` would have quietly broken the one
//! command somebody runs while standing at a lectern.
//!
//! ## What it does not do
//!
//! It does not re-implement anything, parse anything, or decide anything. If
//! what came back is not a directory on disk — a list, JSON, an error message,
//! nothing at all — it is printed and left alone. The test for that is a run
//! that printed JSON: the caller stays where it was.

use crate::command;
use crate::shell::{self, Family};
use crate::terminal::HELD_BY_A_SHELL_FUNCTION;

/// The integration for one family of shells.
pub fn script(family: Family) -> String {
    let wrapped = command::taking_the_caller_with_them();

    match family {
        Family::Posix => posix(&wrapped),
        Family::Fish => fish(&wrapped),
        Family::PowerShell => powershell(&wrapped),
        Family::Nushell => nushell(&wrapped),
    }
}

/// The header every script carries, naming the shells it serves.
///
/// The list comes from the registry rather than from prose here, so a shell
/// added to a family is named by its own script without anybody remembering to
/// come back and say so.
fn header(family: Family, comment: &str, syntax: &str) -> String {
    let serves = shell::sharing(family).join(", ");

    format!(
        "{comment} slidx shell integration for {serves}.\n\
         {comment}\n\
         {comment} Generated by `slidx shell` from the same table the parser reads.\n\
         {comment} Do not edit by hand.\n\
         {comment}\n\
         {comment} Load it from your profile:\n\
         {comment}\n\
         {comment}     {syntax}\n\n"
    )
}

/// sh, bash, zsh and ush.
///
/// Written to the intersection rather than the union: no arrays, no `[[`, no
/// `local`, no `${var,,}`, and every expansion quoted. `local` is the one worth
/// naming — every shell in this family has it and POSIX does not, so the
/// function uses prefixed names and unsets them instead, which is also what
/// leaves nothing behind in an interactive session.
///
/// Verified by running it in all four, which is the only way to know.
fn posix(wrapped: &[&str]) -> String {
    let mut out = header(Family::Posix, "#", "eval \"$(slidx shell sh)\"");

    out.push_str(&format!(
        "slidx() {{\n\
         \x20   case \"${{1:-}}\" in\n\
         \x20   {})\n\
         \x20       __slidx_follow \"$@\"\n\
         \x20       ;;\n\
         \x20   *)\n\
         \x20       command slidx \"$@\"\n\
         \x20       ;;\n\
         \x20   esac\n\
         }}\n\n",
        wrapped.join("|")
    ));

    // `command slidx` rather than `slidx`, or the function calls itself.
    //
    // The path is printed as well as followed, so `cd "$(slidx open x)"` keeps
    // working for everybody who already wrote it that way.
    out.push_str(&format!(
        "__slidx_follow() {{\n\
         \x20   __slidx_out=$({HELD_BY_A_SHELL_FUNCTION}=1 command slidx \"$@\")\n\
         \x20   __slidx_code=$?\n\n\
         \x20   if [ -n \"$__slidx_out\" ]; then\n\
         \x20       printf '%s\\n' \"$__slidx_out\"\n\
         \x20   fi\n\n\
         \x20   if [ \"$__slidx_code\" -eq 0 ] && [ -d \"$__slidx_out\" ]; then\n\
         \x20       # A relative path is prefixed rather than cleared out of\n\
         \x20       # $CDPATH: an assignment in front of `cd` persists, because\n\
         \x20       # cd is a special built-in, and clobbering somebody's CDPATH\n\
         \x20       # to fix our own quoting would be a poor trade.\n\
         \x20       case $__slidx_out in\n\
         \x20       /*) __slidx_where=$__slidx_out ;;\n\
         \x20       *) __slidx_where=./$__slidx_out ;;\n\
         \x20       esac\n\n\
         \x20       cd -- \"$__slidx_where\" || __slidx_code=1\n\
         \x20       unset __slidx_where\n\
         \x20   fi\n\n\
         \x20   unset __slidx_out\n\
         \x20   return $__slidx_code\n\
         }}\n"
    ));

    out
}

/// fish.
///
/// A command substitution in fish returns a list split on newlines, so the
/// check is on the count as well as the type: a run that printed three paths
/// is a list somebody has to read, not a place to go.
fn fish(wrapped: &[&str]) -> String {
    let mut out = header(Family::Fish, "#", "slidx shell fish | source");

    out.push_str(&format!(
        "function slidx --wraps slidx --description 'slidx, and the commands that need your shell'\n\
         \x20   switch \"$argv[1]\"\n\
         \x20   case {}\n\
         \x20       __slidx_follow $argv\n\
         \x20   case '*'\n\
         \x20       command slidx $argv\n\
         \x20   end\n\
         end\n\n",
        wrapped.join(" ")
    ));

    out.push_str(&format!(
        "function __slidx_follow\n\
         \x20   set --local out ({HELD_BY_A_SHELL_FUNCTION}=1 command slidx $argv)\n\
         \x20   set --local code $status\n\n\
         \x20   if test (count $out) -gt 0\n\
         \x20       printf '%s\\n' $out\n\
         \x20   end\n\n\
         \x20   if test $code -eq 0; and test (count $out) -eq 1; and test -d \"$out[1]\"\n\
         \x20       set --local where $out[1]\n\
         \x20       # Relative paths are prefixed so $CDPATH cannot answer\n\
         \x20       # instead of the directory we were handed.\n\
         \x20       if not string match --quiet -- '/*' $where\n\
         \x20           set where ./$where\n\
         \x20       end\n\n\
         \x20       cd $where; or set code 1\n\
         \x20   end\n\n\
         \x20   return $code\n\
         end\n"
    ));

    out
}

/// PowerShell.
///
/// The binary is resolved once, at load, because a function named `slidx`
/// shadows it: `Get-Command -CommandType Application` is the only way to reach
/// past the function that is about to be defined.
fn powershell(wrapped: &[&str]) -> String {
    let mut out = header(Family::PowerShell, "#", "slidx shell powershell | Out-String | iex");

    let list = wrapped.iter().map(|name| format!("'{name}'")).collect::<Vec<_>>().join(", ");

    out.push_str(&format!(
        "$script:SlidxBinary = (Get-Command slidx -CommandType Application -ErrorAction SilentlyContinue |\n\
         \x20   Select-Object -First 1).Source\n\n\
         function slidx {{\n\
         \x20   if (-not $script:SlidxBinary) {{\n\
         \x20       Write-Error 'slidx is not on your PATH, so the shell function has nothing to call.'\n\
         \x20       return\n\
         \x20   }}\n\n\
         \x20   $follows = @({list})\n\n\
         \x20   if ($args.Count -eq 0 -or -not ($follows -contains $args[0])) {{\n\
         \x20       & $script:SlidxBinary @args\n\
         \x20       return\n\
         \x20   }}\n\n\
         \x20   $env:{HELD_BY_A_SHELL_FUNCTION} = '1'\n\
         \x20   try {{\n\
         \x20       $out = & $script:SlidxBinary @args\n\
         \x20       $code = $LASTEXITCODE\n\
         \x20   }}\n\
         \x20   finally {{\n\
         \x20       Remove-Item Env:\\{HELD_BY_A_SHELL_FUNCTION} -ErrorAction SilentlyContinue\n\
         \x20   }}\n\n\
         \x20   if ($out) {{ $out }}\n\n\
         \x20   if ($code -eq 0 -and @($out).Count -eq 1 -and (Test-Path -LiteralPath $out -PathType Container)) {{\n\
         \x20       Set-Location -LiteralPath $out\n\
         \x20   }}\n\n\
         \x20   $global:LASTEXITCODE = $code\n\
         }}\n"
    ));

    out
}

/// Nushell.
///
/// `def --env` is the whole reason this works: a plain Nushell command runs in
/// its own environment and its `cd` would be forgotten on the way out.
///
/// `^slidx` is the external binary rather than this definition, which is how
/// the recursion is avoided — Nushell has no `command` builtin to lean on.
fn nushell(wrapped: &[&str]) -> String {
    let mut out = header(Family::Nushell, "#", "source ~/.config/nushell/slidx-shell.nu");

    let list = wrapped.iter().map(|name| format!("\"{name}\"")).collect::<Vec<_>>().join(" ");

    out.push_str(&format!(
        "def --env slidx [...args] {{\n\
         \x20   if ($args | is-empty) or (($args | first) not-in [{list}]) {{\n\
         \x20       ^slidx ...$args\n\
         \x20       return\n\
         \x20   }}\n\n\
         \x20   let result = (\n\
         \x20       with-env {{{HELD_BY_A_SHELL_FUNCTION}: \"1\"}} {{\n\
         \x20           ^slidx ...$args | complete\n\
         \x20       }}\n\
         \x20   )\n\
         \x20   let out = ($result.stdout | str trim)\n\n\
         \x20   if $out != \"\" {{\n\
         \x20       print $out\n\
         \x20   }}\n\n\
         \x20   if $result.exit_code == 0 and ($out | path type) == \"dir\" {{\n\
         \x20       cd $out\n\
         \x20   }}\n\
         }}\n"
    ));

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn every_script() -> Vec<(Family, String)> {
        [Family::Posix, Family::Fish, Family::PowerShell, Family::Nushell]
            .into_iter()
            .map(|family| (family, script(family)))
            .collect()
    }

    #[test]
    fn every_script_follows_exactly_the_commands_the_table_marks() {
        // The rule this module exists to hold: the list is read, never typed.
        // A command that gains the property gains it in every shell at once.
        for (family, text) in every_script() {
            for name in command::taking_the_caller_with_them() {
                assert!(text.contains(name), "{family:?} does not follow `{name}`");
            }
        }
    }

    #[test]
    fn nothing_else_in_the_table_is_captured() {
        // Capturing a report's standard output costs it its colour and makes it
        // arrive all at once at the end. `slidx doctor` must reach the terminal
        // the way it would have without the function loaded.
        let followed = command::taking_the_caller_with_them();

        for (family, text) in every_script() {
            for entry in command::ALL.iter().filter(|entry| !entry.takes_the_caller_with_it) {
                // The name may appear in prose; what must not appear is the
                // name in the position the script dispatches on.
                for pattern in [
                    format!("|{}|", entry.name),
                    format!("'{}'", entry.name),
                    format!("\"{}\"", entry.name),
                ] {
                    assert!(
                        !text.contains(&pattern),
                        "{family:?} captures `{}`, which is not one of {followed:?}",
                        entry.name
                    );
                }
            }
        }
    }

    #[test]
    fn the_posix_script_uses_nothing_a_posix_shell_does_not_have() {
        // The intersection, not the union. Every one of these works in bash and
        // in zsh and fails in dash, which is /bin/sh on Debian and Ubuntu.
        let text = script(Family::Posix);

        assert!(!text.contains("[["), "{text}");
        assert!(!text.contains("local "), "{text}");
        assert!(!text.contains("function slidx"), "{text}");
        assert!(!text.contains("=("), "{text}");
    }

    #[test]
    fn every_expansion_in_the_posix_script_is_quoted() {
        // A deck under `~/Documents/My Talks` is the ordinary case, not the
        // adversarial one, and an unquoted expansion splits it into two words.
        let text = script(Family::Posix);

        assert!(text.contains("printf '%s\\n' \"$__slidx_out\""), "{text}");
        assert!(text.contains("cd -- \"$__slidx_where\""), "{text}");
        assert!(text.contains("[ -d \"$__slidx_out\" ]"), "{text}");
        assert!(text.contains("command slidx \"$@\""), "{text}");
    }

    #[test]
    fn the_posix_script_is_balanced() {
        // It is eval-ed at every shell start once it is installed, so an
        // unbalanced `case` costs somebody their prompt rather than one
        // command.
        let text = script(Family::Posix);

        assert_eq!(text.matches("case ").count(), text.matches("esac").count());
        assert_eq!(text.matches("() {").count(), 2);
        assert_eq!(text.matches("\n}\n").count(), 2);
    }

    #[test]
    fn the_wrapper_calls_the_binary_rather_than_itself() {
        // A function named `slidx` that ran `slidx` is an infinite loop, and it
        // is the first thing anybody gets wrong here.
        assert!(script(Family::Posix).contains("command slidx"));
        assert!(script(Family::Fish).contains("command slidx"));
        // PowerShell and Nushell have no `command` builtin to lean on.
        assert!(script(Family::PowerShell).contains("Get-Command slidx -CommandType Application"));
        assert!(script(Family::Nushell).contains("^slidx"));
    }

    #[test]
    fn the_directory_is_printed_as_well_as_followed() {
        // `cd "$(slidx open vueconf)"` is in the help text and in people's
        // notes. A function that swallowed the path would break every one of
        // them on the day it was installed.
        assert!(script(Family::Posix).contains("printf '%s\\n' \"$__slidx_out\""));
        assert!(script(Family::Fish).contains("printf '%s\\n' $out"));
        assert!(script(Family::PowerShell).contains("if ($out) { $out }"));
        assert!(script(Family::Nushell).contains("print $out"));
    }

    #[test]
    fn the_exit_code_survives_the_function() {
        // `slidx open nothing-like-this && …` has to still be false. A wrapper
        // that always succeeded would turn a failed search into a cd to your
        // home directory, which is the classic version of this bug.
        assert!(script(Family::Posix).contains("return $__slidx_code"));
        assert!(script(Family::Fish).contains("return $code"));
        assert!(script(Family::PowerShell).contains("$global:LASTEXITCODE = $code"));
    }

    #[test]
    fn nothing_is_followed_unless_it_is_a_directory_that_exists() {
        // `slidx open --json` prints JSON and `slidx open` with no match prints
        // an error. Neither is a place, and a wrapper that tried to cd into one
        // would replace a good message with a bad one.
        assert!(script(Family::Posix).contains("-d \"$__slidx_out\""));
        assert!(script(Family::Fish).contains("test -d \"$out[1]\""));
        assert!(script(Family::PowerShell).contains("-PathType Container"));
        assert!(script(Family::Nushell).contains("path type) == \"dir\""));
    }

    #[test]
    fn each_script_says_which_shells_it_is_for_and_that_it_is_generated() {
        // Somebody finds this in their profile a year later and needs to know
        // whether editing it is pointless.
        for (family, text) in every_script() {
            assert!(text.contains("Generated by `slidx shell`"), "{family:?}");
            assert!(text.contains("Do not edit by hand"), "{family:?}");

            for name in shell::sharing(family) {
                assert!(text.contains(name), "{family:?} does not say it is for {name}");
            }
        }
    }

    #[test]
    fn the_variable_the_wrapper_sets_is_the_one_the_binary_reads() {
        // Set in a script and read in Rust: the two spellings have to be one
        // constant, or the picker falls back to printing a list nobody chose
        // from and nothing says why.
        for (family, text) in every_script() {
            assert!(text.contains(HELD_BY_A_SHELL_FUNCTION), "{family:?}");
        }
    }

    #[test]
    fn the_variable_is_set_for_the_captured_command_only() {
        // Exported for the whole session it would make every later command
        // think its captured output was being read by a shell function.
        let text = script(Family::Posix);

        assert!(!text.contains("export"), "{text}");
        assert!(text.contains(&format!("{HELD_BY_A_SHELL_FUNCTION}=1 command slidx")), "{text}");
    }
}
