/**
 * Builds `@slidx/wasm` from the Rust pipeline.
 *
 * `cargo build` plus `wasm-bindgen` rather than `wasm-pack`. wasm-pack is a
 * wrapper around exactly these two steps that also wants to own the
 * package.json, and the package.json here is hand-written for a reason: the
 * `exports` map has to be right for Node, bundlers, and the browser at once,
 * which is the whole point of choosing WebAssembly over a native addon.
 *
 * `--target web` in every environment. Node 20+ has WebAssembly and fetch, so
 * one artifact serves the dev server, the build, and the editor running in a
 * browser — and "the preview and the build run the same code" stays literally
 * true rather than nearly true.
 */

import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const CRATE = "slidx_wasm";
const OUT = "packages/wasm";
const TARGET = "wasm32-unknown-unknown";

const version = readWorkspaceVersion();

requireMatchingBindgen();

run("cargo", ["build", "-p", CRATE, "--release", "--target", TARGET]);

mkdirSync(join(OUT, "dist"), { recursive: true });

run("wasm-bindgen", [
  `target/${TARGET}/release/${CRATE}.wasm`,
  "--out-dir",
  join(OUT, "dist"),
  "--out-name",
  "slidx",
  "--target",
  "web",
  // Type definitions come from the Rust signatures, so the TypeScript surface
  // cannot drift from what the module actually exports.
  "--typescript",
]);

requireManifestVersion(version);
copyFileSync("LICENSE", join(OUT, "LICENSE"));
writeFileSync(join(OUT, "README.md"), readme());

const bytes = statSync(join(OUT, "dist/slidx_bg.wasm")).size;
process.stdout.write(`\n${OUT} — ${(bytes / 1024).toFixed(0)} kB wasm, version ${version}\n`);

/**
 * The generated glue and the CLI that generates it are one unit.
 *
 * A mismatch fails deep inside wasm-bindgen with a message about recompiling
 * rather than about versions, which costs an afternoon the first time. Reading
 * both and comparing them costs nothing.
 */
function requireMatchingBindgen() {
  const wanted = /wasm-bindgen = "=([^"]+)"/.exec(
    readFileSync("crates/slidx_wasm/Cargo.toml", "utf8"),
  )?.[1];

  let installed;
  try {
    installed = execFileSync("wasm-bindgen", ["--version"], { encoding: "utf8" })
      .trim()
      .split(/\s+/)
      .pop();
  } catch {
    process.stderr.write(
      `wasm-bindgen is not installed.\n  cargo install -f wasm-bindgen-cli --version ${wanted}\n`,
    );
    process.exit(1);
  }

  if (installed !== wanted) {
    process.stderr.write(
      `wasm-bindgen CLI is ${installed} but the crate is pinned to ${wanted}.\n` +
        `  cargo install -f wasm-bindgen-cli --version ${wanted}\n`,
    );
    process.exit(1);
  }
}

/** The manifest is committed, so this only checks it has not drifted. */
function requireManifestVersion(version) {
  const path = join(OUT, "package.json");
  const manifest = JSON.parse(readFileSync(path, "utf8"));

  if (manifest.version !== version) {
    process.stderr.write(`${path} is ${manifest.version} but the Cargo workspace is ${version}.\n`);
    process.exit(1);
  }
}

function readWorkspaceVersion() {
  const manifest = readFileSync("Cargo.toml", "utf8");
  const section = manifest.slice(manifest.indexOf("[workspace.package]"));
  const match = /^version\s*=\s*"([^"]+)"/m.exec(section);

  if (!match) throw new Error("no version in [workspace.package]");
  return match[1];
}

function readme() {
  return `# @slidx/wasm

The [slidx](https://github.com/ubugeeei-prod/slidx) deck pipeline — parser,
step compiler, linter, themes, and renderer — compiled to WebAssembly.

Generated by \`node scripts/build-wasm.mjs\`. Edits here are overwritten; the
source is \`crates/slidx_wasm\`.

\`\`\`js
import init, { buildDeck } from "@slidx/wasm";

await init();
const deck = buildDeck("# Hello\\n\\n---\\n\\n# World\\n");
\`\`\`

Most people want [\`@slidx/vite-plugin\`](https://www.npmjs.com/package/@slidx/vite-plugin)
instead, which calls this for you.
`;
}

function run(command, args) {
  process.stdout.write(`$ ${command} ${args.join(" ")}\n`);
  try {
    execFileSync(command, args, { stdio: "inherit" });
  } catch (error) {
    if (error.code === "ENOENT") {
      process.stderr.write(
        `\n${command} is not installed.\n` +
          (command === "wasm-bindgen"
            ? "  cargo install wasm-bindgen-cli\n"
            : "  rustup target add wasm32-unknown-unknown\n"),
      );
    }
    process.exit(1);
  }
}
