//! `slidx completions` — the command table, written out as shell scripts.
//!
//! Generated, never hand-written. A completion script maintained by hand
//! alongside a parser is two lists that drift, and the drift is silent in the
//! direction that actually happens: a flag added to the parser and not to the
//! completions simply never completes, and nobody files a bug about a thing
//! that quietly does not exist.
//!
//! [`crate::command`] is the one list. The parser reads it, the help text reads
//! it, and these read it — so what completes is what runs, and a test asserts
//! that in both directions for every shell.
//!
//! ## Tested as data
//!
//! No shell is executed to check any of this. Four interpreters would have to
//! be installed on every machine and in CI, three of them are not on a default
//! Linux runner, and the interesting properties are all textual anyway: does
//! every command appear, does every flag appear, and is anything with a quote
//! in it escaped the way that shell escapes things.
//!
//! What that leaves untested is whether each script is *syntactically* valid in
//! its shell, which is a real gap and worth naming. It is covered by the
//! scripts being small, regular, and generated by one function each.

pub mod bash;
pub mod fish;
pub mod powershell;
pub mod zsh;

use crate::args::Matches;
use crate::command::{Command, Flag, ALL};
use crate::Outcome;

/// Writes one shell's script from the command table.
pub type Generator = fn() -> String;

/// The shells slidx can write a script for.
pub const SHELLS: &[(&str, Generator)] = &[
    ("bash", bash::script),
    ("zsh", zsh::script),
    ("fish", fish::script),
    ("powershell", powershell::script),
];

pub fn run(matches: &Matches, _style: &crate::style::Style) -> Outcome {
    let Some(shell) = matches.first_positional() else {
        return Outcome::misuse(needs_a_shell());
    };

    // `pwsh` is what the executable is called, and somebody will type it.
    let wanted = if shell == "pwsh" { "powershell" } else { shell };

    match SHELLS.iter().find(|(name, _)| *name == wanted) {
        Some((_, generate)) => Outcome::out(generate()),
        None => Outcome::misuse(unknown_shell(shell)),
    }
}

/// Every top-level command, for a generator to walk.
pub fn commands() -> &'static [Command] {
    ALL
}

/// The subject line a shell shows next to a completion.
///
/// One line, no newlines, and short — a description that wraps in a completion
/// menu pushes the candidates off the screen, which is the opposite of helping.
pub fn describe(summary: &str) -> &str {
    summary
}

/// `--json`, or `--theme` for one that takes a value.
pub fn long(flag: &Flag) -> String {
    format!("--{}", flag.long)
}

pub fn short(flag: &Flag) -> Option<String> {
    flag.short.map(|letter| format!("-{letter}"))
}

fn needs_a_shell() -> String {
    format!(
        "`slidx completions` needs a shell.\n\n\
         It knows: {}\n\n\
         For example:\n\n  slidx completions fish > ~/.config/fish/completions/slidx.fish\n",
        SHELLS.iter().map(|(name, _)| *name).collect::<Vec<_>>().join(", ")
    )
}

fn unknown_shell(given: &str) -> String {
    format!(
        "slidx does not have completions for `{given}`.\n\n\
         It knows: {}\n",
        SHELLS.iter().map(|(name, _)| *name).collect::<Vec<_>>().join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command;

    fn matches_for(line: &str) -> Matches {
        let argv: Vec<String> = line.split_whitespace().map(String::from).collect();

        match crate::args::parse(&argv) {
            crate::args::Invocation::Run(_, matches) => matches,
            other => panic!("expected a run, got {other:?}"),
        }
    }

    fn scripts() -> Vec<(&'static str, String)> {
        SHELLS.iter().map(|(name, generate)| (*name, generate())).collect()
    }

    #[test]
    fn every_shell_produces_a_script() {
        for (shell, script) in scripts() {
            assert!(!script.trim().is_empty(), "{shell} produced nothing");
            assert!(script.ends_with('\n'), "{shell} does not end with a newline");
        }
    }

    #[test]
    fn every_command_in_the_table_completes_in_every_shell() {
        // The drift this file exists to prevent, in the direction it happens:
        // a command added to the table and not to the completions never
        // completes, and nobody reports a thing that quietly does not exist.
        for (shell, script) in scripts() {
            for entry in command::ALL {
                assert!(script.contains(entry.name), "{shell} does not complete `{}`", entry.name);
            }
        }
    }

    #[test]
    fn every_nested_command_completes_in_every_shell() {
        for (shell, script) in scripts() {
            for parent in command::ALL.iter().filter(|entry| entry.has_subcommands()) {
                for child in parent.subcommands {
                    assert!(
                        script.contains(child.name),
                        "{shell} does not complete `{} {}`",
                        parent.name,
                        child.name
                    );
                }
            }
        }
    }

    /// How one shell spells a flag in its script.
    ///
    /// fish names flags without their dashes — `-l theme` — and the other three
    /// write them out. Both are the same flag, so the check accepts either
    /// rather than pretending there is one spelling.
    fn mentions_flag(script: &str, long: &str) -> bool {
        script.contains(&format!("--{long}")) || script.contains(&format!("-l {long}"))
    }

    #[test]
    fn every_flag_the_parser_accepts_completes_in_every_shell() {
        for (shell, script) in scripts() {
            for entry in command::ALL {
                let places = std::iter::once(entry).chain(entry.subcommands.iter());

                for place in places {
                    for flag in place.all_flags() {
                        assert!(
                            mentions_flag(&script, flag.long),
                            "{shell} does not complete --{} of `{}`",
                            flag.long,
                            place.name
                        );
                    }
                }
            }
        }
    }

    /// The words each script offers as a command, pulled out of its own syntax.
    ///
    /// Prose is not a candidate: `preview`'s summary contains the word "build",
    /// and a scan of every word in the script would read that as slidx
    /// offering a build command. Only the positions that actually complete
    /// count.
    fn candidates(shell: &str, script: &str) -> Vec<String> {
        let quoted = |after: &str| -> Vec<String> {
            script
                .match_indices(after)
                .filter_map(|(at, _)| {
                    let rest = &script[at + after.len()..];
                    rest.split(['\'', ':']).next().map(str::to_string)
                })
                .collect()
        };

        match shell {
            // Space-separated words inside each `compgen -W "…"`.
            "bash" => script
                .match_indices("compgen -W \"")
                .filter_map(|(at, _)| script[at + 12..].split('"').next())
                .flat_map(|list| list.split_whitespace().map(str::to_string))
                .collect(),
            "fish" => quoted("-a '"),
            // Only the `_slidx*_commands` arrays: `_arguments` specs are
            // quoted the same way and are flags, not commands.
            "zsh" => script
                .match_indices("_commands=(")
                .filter_map(|(at, _)| script[at + 11..].split(')').next())
                .flat_map(|block| {
                    block
                        .lines()
                        .filter_map(|line| line.trim().strip_prefix('\''))
                        .filter_map(|entry| entry.split(':').next().map(str::to_string))
                        .collect::<Vec<_>>()
                })
                .collect(),
            "powershell" => quoted("[CompletionResult]::new('"),
            _ => Vec::new(),
        }
    }

    #[test]
    fn nothing_a_command_deliberately_does_not_have_is_offered() {
        // Completing `build` would suggest slidx has one. The declined table
        // exists to say it does not, and a completion offering it would undo
        // that in the place people look first.
        for (shell, script) in scripts() {
            let offered = candidates(shell, &script);

            for (declined, _) in command::DECLINED {
                assert!(
                    !offered.iter().any(|word| word == declined),
                    "{shell} offers the declined `{declined}` among {offered:?}"
                );
            }
        }
    }

    #[test]
    fn the_commands_each_shell_offers_are_the_ones_the_table_declares() {
        // Both directions at once: a command missing from a script never
        // completes, and one in a script that the parser does not know
        // completes into an error.
        let declared: Vec<&str> = command::ALL
            .iter()
            .flat_map(|entry| {
                std::iter::once(entry.name).chain(entry.subcommands.iter().map(|c| c.name))
            })
            .collect();

        for (shell, script) in scripts() {
            let offered = candidates(shell, &script);
            assert!(!offered.is_empty(), "{shell}: nothing was extracted, the test is wrong");

            for word in &offered {
                // Flags reach the same positions in some shells; they are
                // checked separately.
                if word.starts_with('-') {
                    continue;
                }
                assert!(declared.contains(&word.as_str()), "{shell} offers unknown `{word}`");
            }

            for name in &declared {
                assert!(offered.iter().any(|word| word == name), "{shell} never offers `{name}`");
            }
        }
    }

    #[test]
    fn no_script_carries_a_raw_newline_out_of_a_description() {
        // Every description goes into a quoted string in some shell. A newline
        // inside one ends the statement early and the rest of the script
        // becomes commands.
        for entry in command::ALL {
            assert!(!entry.summary.contains('\n'), "{} has a multi-line summary", entry.name);

            for flag in entry.all_flags() {
                assert!(!flag.summary.contains('\n'), "--{} has a multi-line summary", flag.long);
            }
        }
    }

    #[test]
    fn pwsh_is_understood_as_powershell_because_that_is_what_the_binary_is_called() {
        assert_eq!(
            run(&matches_for("completions pwsh"), &crate::style::Style::plain()).stdout,
            run(&matches_for("completions powershell"), &crate::style::Style::plain()).stdout
        );
    }

    #[test]
    fn a_shell_with_no_script_is_told_which_ones_have_one() {
        let outcome = run(&matches_for("completions tcsh"), &crate::style::Style::plain());

        assert_eq!(outcome.code, crate::MISUSE);
        assert!(outcome.stderr.contains("bash"), "{}", outcome.stderr);
        assert!(outcome.stderr.contains("powershell"), "{}", outcome.stderr);
    }

    #[test]
    fn no_shell_at_all_says_what_to_type_and_where_to_put_it() {
        let outcome = run(&matches_for("completions"), &crate::style::Style::plain());

        assert_eq!(outcome.code, crate::MISUSE);
        assert!(outcome.stderr.contains("completions fish"), "{}", outcome.stderr);
    }

    #[test]
    fn a_script_goes_to_standard_output_so_it_can_be_redirected_into_a_file() {
        // The only way anybody installs one of these.
        let outcome = run(&matches_for("completions bash"), &crate::style::Style::plain());

        assert!(!outcome.stdout.is_empty());
        assert!(outcome.stderr.is_empty());
        assert_eq!(outcome.code, crate::OK);
    }

    #[test]
    fn a_script_is_never_coloured_however_the_terminal_is_set() {
        // It is written to a file and read by a shell. An escape sequence in
        // one is a syntax error in a place nobody would think to look.
        for (shell, script) in scripts() {
            assert!(!script.contains('\u{1b}'), "{shell} emitted an escape sequence");
        }
    }
}
