//! `slidx completions` — the command table, written out as shell scripts.
//!
//! Generated, never hand-written. A completion script maintained by hand
//! alongside a parser is two lists that drift, and the drift is silent in the
//! direction that actually happens: a flag added to the parser and not to the
//! completions simply never completes, and nobody files a bug about a thing
//! that quietly does not exist.
//!
//! [`crate::command`] is the one list. The parser reads it, the help text reads
//! it, and these read it — so what completes is what runs, and a test asserts
//! that in both directions for every shell.
//!
//! ## Tested as data
//!
//! No shell is executed to check any of this. Six interpreters would have to be
//! installed on every machine and in CI, most of them are not on a default
//! Linux runner, and the interesting properties are all textual anyway: does
//! every command appear, does every flag appear, and is anything with a quote
//! in it escaped the way that shell escapes things.
//!
//! What that leaves untested is whether each script is *syntactically* valid in
//! its shell, which is a real gap and worth naming. It is covered by the
//! scripts being small, regular, and generated by one function each.
//!
//! ## Which shells, and the one that gets nothing
//!
//! [`crate::shell`] is the list, because a shell is more than its completions —
//! it also has an integration, and sh has the second and can never have the
//! first. Asking for a script for a shell that cannot have one says so in a
//! sentence rather than writing an empty file that looks installed.

pub mod bash;
pub mod fish;
pub mod nushell;
pub mod powershell;
pub mod ush;
pub mod zsh;

use crate::args::Matches;
use crate::command::{Command, Flag, ALL};
use crate::shell::{self, Completions};
use crate::style::{Ink, Style};
use crate::Outcome;

pub fn run(matches: &Matches, style: &Style) -> Outcome {
    let Some(wanted) = matches.first_positional() else {
        return Outcome::misuse(needs_a_shell(style));
    };

    let Some(found) = shell::find(wanted) else {
        return Outcome::misuse(unknown_shell(wanted));
    };

    match found.completions {
        Completions::Script(generate) => Outcome::out(generate()),
        // Not a script that does nothing. Somebody has to be able to stop
        // looking for the flag that would turn this on.
        Completions::Impossible(reason) => {
            Outcome::misuse(format!("{reason}\n\n    eval \"$(slidx shell {})\"\n", found.name))
        }
    }
}

/// Every top-level command, for a generator to walk.
pub fn commands() -> &'static [Command] {
    ALL
}

/// The subject line a shell shows next to a completion.
///
/// One line, no newlines, and short — a description that wraps in a completion
/// menu pushes the candidates off the screen, which is the opposite of helping.
pub fn describe(summary: &str) -> &str {
    summary
}

/// `--json`, or `--theme` for one that takes a value.
pub fn long(flag: &Flag) -> String {
    format!("--{}", flag.long)
}

pub fn short(flag: &Flag) -> Option<String> {
    flag.short.map(|letter| format!("-{letter}"))
}

/// The shells, and where each one's script has to go.
///
/// Printed rather than kept in the help text, because a list in prose is a
/// second list: this one cannot describe a shell the binary does not have.
fn needs_a_shell(style: &Style) -> String {
    let mut text = String::from("`slidx completions` needs a shell.\n\n");

    let width = shell::names().iter().map(|name| name.len()).max().unwrap_or(0);
    for entry in shell::SHELLS {
        let home = match entry.completions_home {
            Some(home) => home.to_string(),
            None => "no programmable completion — `slidx completions sh` says why".to_string(),
        };

        text.push_str(&format!(
            "  {}  {}\n",
            style.pad(Ink::Strong, entry.name, width),
            style.paint(Ink::Faint, home)
        ));
    }

    text.push_str(
        "\nFor example:\n\n  slidx completions fish > ~/.config/fish/completions/slidx.fish\n",
    );

    text
}

fn unknown_shell(given: &str) -> String {
    format!(
        "slidx does not have completions for `{given}`.\n\n\
         It knows: {}\n",
        shell::names().join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command;

    fn matches_for(line: &str) -> Matches {
        let argv: Vec<String> = line.split_whitespace().map(String::from).collect();

        match crate::args::parse(&argv) {
            crate::args::Invocation::Run(_, matches) => matches,
            other => panic!("expected a run, got {other:?}"),
        }
    }

    /// Every shell that has a script, and its script.
    ///
    /// Read out of [`shell::SHELLS`] rather than listed here, so a shell added
    /// to the registry is checked by every test below without one of them being
    /// edited — and a shell added without teaching `candidates` how to read it
    /// fails loudly rather than being skipped.
    fn scripts() -> Vec<(&'static str, String)> {
        shell::completing().map(|(entry, generate)| (entry.name, generate())).collect()
    }

    #[test]
    fn every_shell_produces_a_script() {
        for (shell, script) in scripts() {
            assert!(!script.trim().is_empty(), "{shell} produced nothing");
            assert!(script.ends_with('\n'), "{shell} does not end with a newline");
        }
    }

    #[test]
    fn every_command_in_the_table_completes_in_every_shell() {
        // The drift this file exists to prevent, in the direction it happens:
        // a command added to the table and not to the completions never
        // completes, and nobody reports a thing that quietly does not exist.
        for (shell, script) in scripts() {
            for entry in command::ALL {
                assert!(script.contains(entry.name), "{shell} does not complete `{}`", entry.name);
            }
        }
    }

    #[test]
    fn every_nested_command_completes_in_every_shell() {
        for (shell, script) in scripts() {
            for parent in command::ALL.iter().filter(|entry| entry.has_subcommands()) {
                for child in parent.subcommands {
                    assert!(
                        script.contains(child.name),
                        "{shell} does not complete `{} {}`",
                        parent.name,
                        child.name
                    );
                }
            }
        }
    }

    /// How one shell spells a flag in its script.
    ///
    /// fish names flags without their dashes — `-l theme` — and the others write
    /// them out. Both are the same flag, so the check accepts either rather than
    /// pretending there is one spelling.
    fn mentions_flag(script: &str, long: &str) -> bool {
        script.contains(&format!("--{long}")) || script.contains(&format!("-l {long}"))
    }

    /// Whether a shell has to be told about a flag at all.
    ///
    /// Nushell puts `--help` in every signature it is given and rejects a second
    /// declaration of it — see [`nushell`]. So the one flag Nushell must not be
    /// told about is the one it already knows, and that is a property of Nushell
    /// rather than a gap in the generated file.
    fn has_to_be_told(shell: &str, long: &str) -> bool {
        !(shell == "nushell" && long == "help")
    }

    #[test]
    fn every_flag_the_parser_accepts_completes_in_every_shell() {
        for (shell, script) in scripts() {
            for entry in command::ALL {
                let places = std::iter::once(entry).chain(entry.subcommands.iter());

                for place in places {
                    for flag in place.all_flags().iter().filter(|f| has_to_be_told(shell, f.long)) {
                        assert!(
                            mentions_flag(&script, flag.long),
                            "{shell} does not complete --{} of `{}`",
                            flag.long,
                            place.name
                        );
                    }
                }
            }
        }
    }

    /// The words each script offers as a command, pulled out of its own syntax.
    ///
    /// Prose is not a candidate: `preview`'s summary contains the word "build",
    /// and a scan of every word in the script would read that as slidx
    /// offering a build command. Only the positions that actually complete
    /// count.
    fn candidates(shell: &str, script: &str) -> Vec<String> {
        let quoted = |after: &str| -> Vec<String> {
            script
                .match_indices(after)
                .filter_map(|(at, _)| {
                    let rest = &script[at + after.len()..];
                    rest.split(['\'', ':']).next().map(str::to_string)
                })
                .collect()
        };

        match shell {
            // Space-separated words inside each `compgen -W "…"`.
            "bash" => script
                .match_indices("compgen -W \"")
                .filter_map(|(at, _)| script[at + 12..].split('"').next())
                .flat_map(|list| list.split_whitespace().map(str::to_string))
                .collect(),
            "fish" => quoted("-a '"),
            // Only the `_slidx*_commands` arrays: `_arguments` specs are
            // quoted the same way and are flags, not commands.
            "zsh" => script
                .match_indices("_commands=(")
                .filter_map(|(at, _)| script[at + 11..].split(')').next())
                .flat_map(|block| {
                    block
                        .lines()
                        .filter_map(|line| line.trim().strip_prefix('\''))
                        .filter_map(|entry| entry.split(':').next().map(str::to_string))
                        .collect::<Vec<_>>()
                })
                .collect(),
            "powershell" => quoted("[CompletionResult]::new('"),
            // The name each `extern` declares, with `slidx ` taken off the
            // front so what is left is the word that completes.
            "nushell" => script
                .match_indices("extern \"slidx")
                .filter_map(|(at, _)| script[at + 13..].split('"').next())
                .flat_map(|rest| rest.split_whitespace().map(str::to_string).collect::<Vec<_>>())
                .collect(),
            // Every `&[&str]` of command names, which is what ush dispatches
            // on. `SLIDX_OPTIONS` is flags and is checked separately.
            "ush" => script
                .match_indices("_COMMANDS: &[&str] = &[")
                .filter_map(|(at, _)| script[at + 23..].split(']').next())
                .flat_map(|block| {
                    block
                        .lines()
                        .filter_map(|line| line.trim().strip_prefix('"'))
                        .filter_map(|entry| entry.split('"').next().map(str::to_string))
                        .collect::<Vec<_>>()
                })
                .collect(),
            // Deliberately not a fallback that returns nothing: a shell added
            // to the registry without being taught here would silently stop
            // being checked, and the check is the point.
            other => panic!("nothing knows how to read {other}'s script — teach `candidates`"),
        }
    }

    #[test]
    fn nothing_a_command_deliberately_does_not_have_is_offered() {
        // Completing `build` would suggest slidx has one. The declined table
        // exists to say it does not, and a completion offering it would undo
        // that in the place people look first.
        for (shell, script) in scripts() {
            let offered = candidates(shell, &script);

            for (declined, _) in command::DECLINED {
                assert!(
                    !offered.iter().any(|word| word == declined),
                    "{shell} offers the declined `{declined}` among {offered:?}"
                );
            }
        }
    }

    #[test]
    fn the_commands_each_shell_offers_are_the_ones_the_table_declares() {
        // Both directions at once: a command missing from a script never
        // completes, and one in a script that the parser does not know
        // completes into an error.
        let declared: Vec<&str> = command::ALL
            .iter()
            .flat_map(|entry| {
                std::iter::once(entry.name).chain(entry.subcommands.iter().map(|c| c.name))
            })
            .collect();

        for (shell, script) in scripts() {
            let offered = candidates(shell, &script);
            assert!(!offered.is_empty(), "{shell}: nothing was extracted, the test is wrong");

            for word in &offered {
                // Flags reach the same positions in some shells; they are
                // checked separately.
                if word.starts_with('-') {
                    continue;
                }
                assert!(declared.contains(&word.as_str()), "{shell} offers unknown `{word}`");
            }

            for name in &declared {
                assert!(offered.iter().any(|word| word == name), "{shell} never offers `{name}`");
            }
        }
    }

    #[test]
    fn no_script_carries_a_raw_newline_out_of_a_description() {
        // Every description goes into a quoted string in some shell. A newline
        // inside one ends the statement early and the rest of the script
        // becomes commands.
        for entry in command::ALL {
            assert!(!entry.summary.contains('\n'), "{} has a multi-line summary", entry.name);

            for flag in entry.all_flags() {
                assert!(!flag.summary.contains('\n'), "--{} has a multi-line summary", flag.long);
            }
        }
    }

    #[test]
    fn pwsh_is_understood_as_powershell_because_that_is_what_the_binary_is_called() {
        assert_eq!(
            run(&matches_for("completions pwsh"), &crate::style::Style::plain()).stdout,
            run(&matches_for("completions powershell"), &crate::style::Style::plain()).stdout
        );
    }

    #[test]
    fn a_shell_with_no_script_is_told_which_ones_have_one() {
        let outcome = run(&matches_for("completions tcsh"), &crate::style::Style::plain());

        assert_eq!(outcome.code, crate::MISUSE);
        for (entry, _) in shell::completing() {
            assert!(outcome.stderr.contains(entry.name), "{}", outcome.stderr);
        }
    }

    #[test]
    fn no_shell_at_all_says_what_to_type_and_where_every_script_goes() {
        let outcome = run(&matches_for("completions"), &crate::style::Style::plain());

        assert_eq!(outcome.code, crate::MISUSE);
        assert!(outcome.stderr.contains("completions fish"), "{}", outcome.stderr);

        for (entry, _) in shell::completing() {
            let home = entry.completions_home.expect("a script goes somewhere");
            assert!(outcome.stderr.contains(home), "{} has nowhere named", entry.name);
        }
    }

    #[test]
    fn a_shell_that_cannot_complete_at_all_is_told_why_rather_than_handed_a_stub() {
        // The failure this exists to prevent is quiet: a script that installs
        // cleanly, sits on the fpath, and makes tab do exactly what it did
        // before. Somebody would spend an evening on that.
        let outcome = run(&matches_for("completions sh"), &crate::style::Style::plain());

        assert_eq!(outcome.code, crate::MISUSE);
        assert!(outcome.stdout.is_empty(), "a stub was written: {}", outcome.stdout);
        assert!(outcome.stderr.contains("no programmable completion"), "{}", outcome.stderr);
        // And the thing sh does have, in the same breath.
        assert!(outcome.stderr.contains("slidx shell sh"), "{}", outcome.stderr);
    }

    #[test]
    fn every_shell_with_a_script_is_reachable_by_the_name_its_binary_has() {
        // `pwsh` and `nu` are what people type. A registry entry nobody can
        // name is a script nobody can install.
        for (entry, _) in shell::completing() {
            for spelling in [entry.name].iter().chain(entry.aliases.iter()) {
                let outcome = run(
                    &matches_for(&format!("completions {spelling}")),
                    &crate::style::Style::plain(),
                );

                assert_eq!(outcome.code, crate::OK, "{spelling}: {}", outcome.stderr);
            }
        }
    }

    #[test]
    fn a_script_goes_to_standard_output_so_it_can_be_redirected_into_a_file() {
        // The only way anybody installs one of these.
        let outcome = run(&matches_for("completions bash"), &crate::style::Style::plain());

        assert!(!outcome.stdout.is_empty());
        assert!(outcome.stderr.is_empty());
        assert_eq!(outcome.code, crate::OK);
    }

    #[test]
    fn a_script_is_never_coloured_however_the_terminal_is_set() {
        // It is written to a file and read by a shell. An escape sequence in
        // one is a syntax error in a place nobody would think to look.
        for (shell, script) in scripts() {
            assert!(!script.contains('\u{1b}'), "{shell} emitted an escape sequence");
        }
    }
}
