//! Which shells slidx knows, and what each of them can be given.
//!
//! Two different things are written for a shell and they are constantly
//! confused, so this module holds both and keeps them apart:
//!
//! - a **completion script**, which teaches the shell what `slidx <tab>` should
//!   offer. Generated per shell from [`crate::command`] by
//!   [`crate::completions`].
//! - the **integration**, one wrapper function that lets a slidx command change
//!   the directory the caller is standing in. Generated by
//!   [`integration`].
//!
//! A shell can have both, or only the second. Nothing has only the first: the
//! integration is plain function-calls-a-program and every shell in use can do
//! it, while programmable completion is a feature a shell either has or does
//! not.
//!
//! ## Why the honesty is a data structure
//!
//! [`Completions::Impossible`] exists so that "slidx cannot complete for this
//! shell" is a sentence somebody reads rather than an empty file they install
//! and then wonder about. A stub script that silently does nothing is the worst
//! of the three outcomes — it looks installed, it is on the fpath, and pressing
//! tab does the same thing it did before.

pub mod integration;

use crate::args::Matches;
use crate::style::{Ink, Style};
use crate::Outcome;

/// Writes one shell's script from the command table.
pub type Generator = fn() -> String;

/// What slidx can write to complete its own command line in a shell.
#[derive(Debug, Clone, Copy)]
pub enum Completions {
    /// A script, generated from the command table.
    Script(Generator),
    /// This shell has no programmable completion, and no script would give it
    /// any. The sentence says why, because "unsupported" reads as an omission
    /// somebody could file a bug about, and this is not one.
    Impossible(&'static str),
}

/// Which syntax a shell's integration is written in.
///
/// Four families rather than seven scripts: the wrapper needs nothing that is
/// not in POSIX sh, so one script serves sh, bash, zsh and ush — verified by
/// running it in all four rather than assumed from their family tree.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Family {
    Posix,
    Fish,
    PowerShell,
    Nushell,
}

/// One shell, and everything slidx knows about writing for it.
#[derive(Debug, Clone, Copy)]
pub struct Shell {
    /// What somebody types: `slidx completions zsh`.
    pub name: &'static str,
    /// Other names for the same shell. `pwsh` is what the executable is
    /// called, `nu` likewise, and somebody will type those.
    pub aliases: &'static [&'static str],
    pub completions: Completions,
    /// Where a completion script has to go for the shell to find it.
    ///
    /// `None` where there is no script to put anywhere. Held here rather than
    /// written into the help text, so the instructions cannot describe a shell
    /// the binary does not have.
    pub completions_home: Option<&'static str>,
    pub family: Family,
    /// The file the integration line goes in.
    pub profile: &'static str,
}

pub const SHELLS: &[Shell] = &[
    Shell {
        name: "sh",
        // Both are the same job with the same grammar, and somebody whose
        // /bin/sh is one of them will type its name.
        aliases: &["dash", "ash"],
        completions: Completions::Impossible(
            "\
sh has no programmable completion. There is no hook to register a completer
with — it is not missing from slidx, it is missing from the shell, and no
script anybody writes will add one.

Everything else works: the integration below is plain POSIX sh, and every
slidx command behaves the same there as anywhere.",
        ),
        completions_home: None,
        family: Family::Posix,
        profile: "~/.profile",
    },
    Shell {
        name: "bash",
        aliases: &[],
        completions: Completions::Script(crate::completions::bash::script),
        completions_home: Some("~/.local/share/bash-completion/completions/slidx"),
        family: Family::Posix,
        profile: "~/.bashrc",
    },
    Shell {
        name: "zsh",
        aliases: &[],
        completions: Completions::Script(crate::completions::zsh::script),
        completions_home: Some("~/.zfunc/_slidx"),
        family: Family::Posix,
        profile: "~/.zshrc",
    },
    Shell {
        name: "fish",
        aliases: &[],
        completions: Completions::Script(crate::completions::fish::script),
        completions_home: Some("~/.config/fish/completions/slidx.fish"),
        family: Family::Fish,
        profile: "~/.config/fish/config.fish",
    },
    Shell {
        name: "powershell",
        aliases: &["pwsh"],
        completions: Completions::Script(crate::completions::powershell::script),
        completions_home: Some("$PROFILE (appended)"),
        family: Family::PowerShell,
        profile: "$PROFILE",
    },
    Shell {
        name: "nushell",
        aliases: &["nu"],
        completions: Completions::Script(crate::completions::nushell::script),
        completions_home: Some("~/.config/nushell/slidx.nu, sourced from config.nu"),
        family: Family::Nushell,
        profile: "~/.config/nushell/config.nu",
    },
    Shell {
        name: "ush",
        aliases: &[],
        completions: Completions::Script(crate::completions::ush::script),
        // Not a path in anybody's config directory, and that is the whole
        // point: ush completes from a catalogue compiled into itself, so what
        // slidx can write is the entry, not a script to install.
        completions_home: Some("ush's own tree — the file says where"),
        family: Family::Posix,
        profile: "~/.config/ush/.config.ush",
    },
];

/// A shell by the name somebody typed, or by one of its other names.
pub fn find(name: &str) -> Option<&'static Shell> {
    SHELLS.iter().find(|shell| shell.name == name || shell.aliases.contains(&name))
}

/// Every shell slidx knows, under its primary name.
pub fn names() -> Vec<&'static str> {
    SHELLS.iter().map(|shell| shell.name).collect()
}

/// Every shell there is a completion script for, and the script.
pub fn completing() -> impl Iterator<Item = (&'static Shell, Generator)> {
    SHELLS.iter().filter_map(|shell| match shell.completions {
        Completions::Script(generate) => Some((shell, generate)),
        Completions::Impossible(_) => None,
    })
}

/// Every shell whose integration is written in this syntax.
///
/// So a generated script can name the shells it serves without a second list
/// saying which those are.
pub fn sharing(family: Family) -> Vec<&'static str> {
    SHELLS.iter().filter(|shell| shell.family == family).map(|shell| shell.name).collect()
}

/// `slidx shell <name>`.
pub fn run(matches: &Matches, style: &Style) -> Outcome {
    let Some(name) = matches.first_positional() else {
        return Outcome::misuse(needs_a_shell(style));
    };

    match find(name) {
        Some(shell) => Outcome::out(integration::script(shell.family)),
        None => Outcome::misuse(unknown_shell(name, style)),
    }
}

/// The list, with the file each shell's line goes in.
fn needs_a_shell(style: &Style) -> String {
    let mut text = String::from(
        "`slidx shell` needs a shell.\n\n\
         It writes a function that lets slidx change the directory you are\n\
         standing in — which a program cannot do for the shell that ran it.\n\n",
    );

    let width = SHELLS.iter().map(|shell| shell.name.len()).max().unwrap_or(0);
    for shell in SHELLS {
        text.push_str(&format!(
            "  {}  {}\n",
            style.pad(Ink::Strong, shell.name, width),
            style.paint(Ink::Faint, format!("in {}", shell.profile))
        ));
    }

    text.push_str("\nPut the line in that file:\n\n  eval \"$(slidx shell sh)\"\n");
    text
}

fn unknown_shell(given: &str, style: &Style) -> String {
    format!(
        "slidx has no shell integration for `{given}`.\n\n\
         It knows: {}\n\n\
         The integration is not the completions. `slidx completions` is that.\n",
        style.paint(Ink::Strong, names().join(", "))
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command;
    use crate::MISUSE;

    fn matches_for(line: &str) -> Matches {
        let argv: Vec<String> = line.split_whitespace().map(String::from).collect();

        match crate::args::parse(&argv) {
            crate::args::Invocation::Run(_, matches) => matches,
            other => panic!("expected a run, got {other:?}"),
        }
    }

    #[test]
    fn every_shell_is_named_once_across_its_name_and_its_aliases() {
        // Two shells answering to one word would make the lookup depend on
        // table order, which is the sort of thing nobody notices until a
        // completion script arrives for the wrong shell.
        let mut spellings: Vec<&str> = SHELLS
            .iter()
            .flat_map(|shell| [shell.name].into_iter().chain(shell.aliases.iter().copied()))
            .collect();
        let total = spellings.len();
        spellings.sort_unstable();
        spellings.dedup();

        assert_eq!(spellings.len(), total, "two shells answer to the same name");
    }

    #[test]
    fn a_shell_is_found_by_the_name_its_executable_actually_has() {
        // `pwsh` and `nu` are what people type, because they are what the
        // binaries are called.
        assert_eq!(find("pwsh").map(|shell| shell.name), Some("powershell"));
        assert_eq!(find("nu").map(|shell| shell.name), Some("nushell"));
        assert_eq!(find("dash").map(|shell| shell.name), Some("sh"));
        assert!(find("tcsh").is_none());
    }

    #[test]
    fn every_shell_says_where_its_integration_line_goes() {
        // The one question somebody has after reading the script.
        for shell in SHELLS {
            assert!(!shell.profile.is_empty(), "{} does not say where its line goes", shell.name);
        }
    }

    #[test]
    fn a_shell_with_a_completion_script_says_where_the_script_goes() {
        for (shell, _) in completing() {
            assert!(
                shell.completions_home.is_some(),
                "{} has a script and nowhere to put it",
                shell.name
            );
        }
    }

    #[test]
    fn a_shell_with_no_completions_explains_itself_in_a_sentence() {
        // Not "unsupported". Somebody has to be able to stop looking for the
        // flag that would turn it on.
        for shell in SHELLS {
            if let Completions::Impossible(reason) = shell.completions {
                assert!(reason.contains(shell.name), "{}'s reason does not name it", shell.name);
                assert!(reason.len() > 40, "{}'s reason is a label, not a reason", shell.name);
                assert!(
                    shell.completions_home.is_none(),
                    "{} has nowhere to put a script it does not have",
                    shell.name
                );
            }
        }
    }

    #[test]
    fn every_shell_gets_an_integration_even_where_completions_are_impossible() {
        // The whole point of keeping the two apart. A shell that cannot
        // complete can still be taken somewhere.
        for shell in SHELLS {
            let script = integration::script(shell.family);

            assert!(!script.trim().is_empty(), "{} gets no integration", shell.name);
            for name in command::taking_the_caller_with_them() {
                assert!(script.contains(name), "{} does not follow `{name}`", shell.name);
            }
        }
    }

    #[test]
    fn asking_for_one_shells_integration_writes_it_to_standard_output() {
        // Redirected or eval-ed, which are the only two ways anybody uses it.
        let outcome = run(&matches_for("shell sh"), &Style::plain());

        assert!(outcome.stdout.contains("slidx()"), "{}", outcome.stdout);
        assert!(outcome.stderr.is_empty());
        assert_eq!(outcome.code, crate::OK);
    }

    #[test]
    fn shells_in_one_family_are_handed_the_same_script() {
        // bash and sh differ in a great many ways and in none that this
        // function uses, so writing two would be writing one twice.
        assert_eq!(integration::script(Family::Posix), integration::script(Family::Posix));
        assert_eq!(
            run(&matches_for("shell bash"), &Style::plain()).stdout,
            run(&matches_for("shell ush"), &Style::plain()).stdout
        );
    }

    #[test]
    fn no_shell_at_all_lists_them_with_the_file_the_line_goes_in() {
        let outcome = run(&matches_for("shell"), &Style::plain());

        assert_eq!(outcome.code, MISUSE);
        for shell in SHELLS {
            assert!(outcome.stderr.contains(shell.name), "{}", outcome.stderr);
            assert!(outcome.stderr.contains(shell.profile), "{}", outcome.stderr);
        }
    }

    #[test]
    fn a_shell_nobody_has_heard_of_is_told_which_ones_slidx_knows() {
        let outcome = run(&matches_for("shell tcsh"), &Style::plain());

        assert_eq!(outcome.code, MISUSE);
        assert!(outcome.stderr.contains("tcsh"), "{}", outcome.stderr);
        assert!(outcome.stderr.contains("fish"), "{}", outcome.stderr);
    }

    #[test]
    fn nothing_written_for_a_shell_is_ever_coloured() {
        // It is eval-ed by a shell or written to a file it reads at every
        // start. An escape sequence in one is a syntax error somewhere nobody
        // would think to look.
        for shell in SHELLS {
            assert!(!integration::script(shell.family).contains('\u{1b}'), "{}", shell.name);
        }

        assert!(!run(&matches_for("shell fish"), &Style::colored()).stdout.contains('\u{1b}'));
    }
}
