//! bash completions.
//!
//! bash has no notion of a command tree, so the script carries one: a `case`
//! over the first word after `slidx`, and a second `case` inside it for a
//! command that has children. That is more machinery than fish needs and it is
//! the shape bash gives you.
//!
//! bash shows no descriptions, so only the words are emitted. Writing them into
//! the script anyway — as comments nobody reads — would be padding.

use crate::command::{Command, ALL, ROOT};

/// Words for `compgen -W`, space-separated inside one quoted string.
///
/// Every word here is a command or flag name, and both are already constrained
/// to lowercase, digits, `-` and `/` by a test in [`crate::command`] — so there
/// is nothing to escape, and a quote appearing in one later would be a bug in
/// the table rather than something to paper over here.
fn words(items: impl Iterator<Item = String>) -> String {
    items.collect::<Vec<_>>().join(" ")
}

pub fn script() -> String {
    let mut out = String::from(
        "# slidx completions for bash.\n\
         #\n\
         # Generated by `slidx completions bash` from the same table the parser\n\
         # reads, so what completes is what runs. Do not edit by hand.\n\n\
         _slidx() {\n\
         \x20   local cur prev command sub\n\
         \x20   cur=\"${COMP_WORDS[COMP_CWORD]}\"\n\
         \x20   prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\
         \x20   command=\"\"\n\
         \x20   sub=\"\"\n\n\
         \x20   # The first two words that are not flags: the command, and its\n\
         \x20   # subcommand where it has one.\n\
         \x20   local index\n\
         \x20   for (( index=1; index < COMP_CWORD; index++ )); do\n\
         \x20       case \"${COMP_WORDS[index]}\" in\n\
         \x20           -*) continue ;;\n\
         \x20       esac\n\
         \x20       if [[ -z $command ]]; then command=\"${COMP_WORDS[index]}\"\n\
         \x20       elif [[ -z $sub ]]; then sub=\"${COMP_WORDS[index]}\"\n\
         \x20       fi\n\
         \x20   done\n\n",
    );

    out.push_str(&format!(
        "    if [[ -z $command ]]; then\n\
         \x20       COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n\
         \x20       return\n\
         \x20   fi\n\n",
        words(
            ALL.iter()
                .map(|entry| entry.name.to_string())
                .chain(ROOT.iter().map(|flag| format!("--{}", flag.long)))
        )
    ));

    out.push_str("    case \"$command\" in\n");
    for entry in ALL {
        out.push_str(&arm(entry));
    }
    out.push_str("    esac\n}\n\ncomplete -F _slidx slidx\n");

    out
}

/// One `case` arm: a command, and its children where it has them.
fn arm(entry: &'static Command) -> String {
    let flags = words(entry.all_flags().iter().map(|flag| format!("--{}", flag.long)));

    if !entry.has_subcommands() {
        return format!(
            "        {})\n\
             \x20           COMPREPLY=( $(compgen -W \"{flags}\" -- \"$cur\") )\n\
             \x20           return\n\
             \x20           ;;\n",
            entry.name
        );
    }

    let mut out = format!("        {})\n            case \"$sub\" in\n", entry.name);

    for child in entry.subcommands {
        out.push_str(&format!(
            "                {})\n\
             \x20                   COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n\
             \x20                   return\n\
             \x20                   ;;\n",
            child.name,
            words(child.all_flags().iter().map(|flag| format!("--{}", flag.long)))
        ));
    }

    // No subcommand yet: offer the children, and the parent's own flags.
    out.push_str(&format!(
        "                *)\n\
         \x20                   COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n\
         \x20                   return\n\
         \x20                   ;;\n\
         \x20           esac\n\
         \x20           ;;\n",
        words(
            entry
                .subcommands
                .iter()
                .map(|child| child.name.to_string())
                .chain(entry.all_flags().iter().map(|flag| format!("--{}", flag.long)))
        )
    ));

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_top_level_offers_every_command_and_the_root_flags() {
        // Derived from the table rather than spelled out. A literal list here
        // is a second place a command has to be added, and it failed the first
        // time one was — which is the drift this whole module exists to stop.
        let text = script();
        let expected = words(
            ALL.iter()
                .map(|entry| entry.name.to_string())
                .chain(ROOT.iter().map(|flag| format!("--{}", flag.long))),
        );

        assert!(text.contains(&expected), "{text}");
        assert!(text.contains("--help --version"), "{text}");
    }

    #[test]
    fn every_declared_command_is_offered_by_name() {
        // The same claim stated so a failure names the command that is
        // missing, rather than printing the whole script and leaving a reader
        // to diff two long lines by eye.
        let text = script();

        for entry in ALL {
            assert!(text.contains(entry.name), "{} is declared and never offered", entry.name);
        }
    }

    #[test]
    fn a_command_with_children_offers_them_before_one_is_chosen() {
        assert!(script().contains("current list install use remove"), "{}", script());
    }

    #[test]
    fn a_chosen_child_offers_its_own_flags_and_not_its_siblings() {
        let text = script();

        // `version install` takes --use and --force; `version use` takes
        // neither, and offering them there would suggest they do something.
        assert!(text.contains("--use --force --help"), "{text}");
    }

    #[test]
    fn flags_are_skipped_when_looking_for_the_command() {
        // `slidx --help version <tab>` and `slidx version --json <tab>` both
        // have to find `version`, or the completion falls back to the top
        // level and offers commands in the middle of a line.
        assert!(script().contains("-*) continue ;;"));
    }

    #[test]
    fn the_function_is_registered_for_the_binary() {
        assert!(script().contains("complete -F _slidx slidx"));
    }

    #[test]
    fn the_script_says_it_is_generated_and_where_from() {
        let text = script();

        assert!(text.contains("Generated by `slidx completions bash`"), "{text}");
        assert!(text.contains("Do not edit by hand"), "{text}");
    }

    #[test]
    fn every_case_arm_is_closed() {
        // The one structural property worth checking without a shell: an
        // unbalanced `case` is a syntax error that takes the whole file with
        // it, and the file is sourced at every shell start.
        let text = script();

        assert_eq!(text.matches("case \"").count(), text.matches("esac").count());
    }

    #[test]
    fn nothing_in_the_word_lists_needs_escaping() {
        // Command and flag names are constrained to lowercase, digits, `-` and
        // `/` by the table's own tests. This is the assertion that connects
        // that constraint to this file's decision not to quote anything.
        for entry in crate::command::ALL {
            assert!(entry.name.chars().all(|c| c.is_ascii_alphanumeric() || c == '-'));

            for flag in entry.all_flags() {
                assert!(flag.long.chars().all(|c| c.is_ascii_alphanumeric() || c == '-'));
            }
        }
    }
}
