//! fish completions.
//!
//! fish's model fits the command table almost exactly: every completion is one
//! `complete` line carrying its own condition, so a nested command needs no
//! state machine — just a condition saying which subcommand is already on the
//! line. It is the shell where the generated script reads most like the table
//! it came from.
//!
//! Descriptions are shown inline in fish's menu, so every command and flag
//! carries its summary.

use super::{long, short};
use crate::command::{Command, ALL, ROOT};

/// Single quotes, which is all fish needs: inside them only `'` and `\` are
/// special, and both escape with a backslash.
fn quote(text: &str) -> String {
    format!("'{}'", text.replace('\\', "\\\\").replace('\'', "\\'"))
}

pub fn script() -> String {
    let mut out = String::from(
        "# slidx completions for fish.\n\
         #\n\
         # Generated by `slidx completions fish` from the same table the parser\n\
         # reads, so what completes is what runs. Do not edit by hand.\n\n\
         # slidx takes no bare file arguments at the top level.\n\
         complete -c slidx -f\n\n",
    );

    for flag in ROOT {
        out.push_str(&format!(
            "complete -c slidx -n __fish_use_subcommand {} -d {}\n",
            flag_switches(flag),
            quote(flag.summary)
        ));
    }

    out.push('\n');
    for entry in ALL {
        out.push_str(&format!(
            "complete -c slidx -n __fish_use_subcommand -a {} -d {}\n",
            quote(entry.name),
            quote(entry.summary)
        ));
    }

    for entry in ALL {
        out.push('\n');
        out.push_str(&command(entry));
    }

    out
}

/// Every completion that applies once one command is on the line.
fn command(entry: &'static Command) -> String {
    let mut out = format!("# slidx {}\n", entry.name);

    for child in entry.subcommands {
        // `__fish_seen_subcommand_from` is true anywhere after the word, so a
        // second condition keeps the children from being offered again once
        // one of them has been chosen.
        out.push_str(&format!(
            "complete -c slidx -n {} -a {} -d {}\n",
            quote(&format!(
                "__fish_seen_subcommand_from {}; and not __fish_seen_subcommand_from {}",
                entry.name,
                entry.subcommands.iter().map(|child| child.name).collect::<Vec<_>>().join(" ")
            )),
            quote(child.name),
            quote(child.summary)
        ));
    }

    for flag in entry.all_flags() {
        out.push_str(&format!(
            "complete -c slidx -n {} {} -d {}\n",
            quote(&format!("__fish_seen_subcommand_from {}", entry.name)),
            flag_switches(flag),
            quote(flag.summary)
        ));
    }

    for child in entry.subcommands {
        for flag in child.all_flags() {
            out.push_str(&format!(
                "complete -c slidx -n {} {} -d {}\n",
                quote(&format!(
                    "__fish_seen_subcommand_from {}; and __fish_seen_subcommand_from {}",
                    entry.name, child.name
                )),
                flag_switches(flag),
                quote(flag.summary)
            ));
        }
    }

    out
}

/// `-s h -l help`, plus `-r` for a flag that wants a value.
fn flag_switches(flag: &crate::command::Flag) -> String {
    let mut switches = String::new();

    if let Some(letter) = short(flag) {
        switches.push_str(&format!("-s {} ", letter.trim_start_matches('-')));
    }

    switches.push_str(&format!("-l {}", long(flag).trim_start_matches("--")));

    // `-r` makes fish require an argument, so it stops offering other flags
    // until one is typed.
    if flag.takes_value() {
        switches.push_str(" -r");
    }

    switches
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_top_level_command_is_offered_only_before_a_subcommand_is_chosen() {
        let text = script();

        assert!(text.contains("complete -c slidx -n __fish_use_subcommand -a 'doctor'"), "{text}");
    }

    #[test]
    fn a_nested_command_is_offered_after_its_parent() {
        assert!(script().contains("__fish_seen_subcommand_from version"));
        assert!(script().contains("-a 'install'"));
    }

    #[test]
    fn a_nested_command_stops_being_offered_once_one_is_chosen() {
        // Otherwise `slidx version use ` keeps suggesting `list`, `install`
        // and `current` as though they could follow it.
        assert!(script()
            .contains("and not __fish_seen_subcommand_from current list install use remove"));
    }

    #[test]
    fn a_flag_that_takes_a_value_is_marked_as_requiring_one() {
        // So fish stops offering other flags until a value is typed.
        assert!(script().contains("-l theme -r"), "{}", script());
    }

    #[test]
    fn a_switch_is_not_marked_as_requiring_a_value() {
        assert!(script().contains("-l json -d"), "{}", script());
        assert!(!script().contains("-l json -r"));
    }

    #[test]
    fn a_short_letter_is_offered_alongside_its_long_name() {
        assert!(script().contains("-s h -l help"));
        assert!(script().contains("-s V -l version"));
    }

    #[test]
    fn nothing_completes_a_bare_file_name_at_the_top_level() {
        // `slidx <tab>` should offer commands, not the contents of the
        // directory somebody happens to be standing in.
        assert!(script().contains("complete -c slidx -f"));
    }

    #[test]
    fn a_description_containing_a_quote_is_escaped_rather_than_ending_the_string() {
        // Nothing in the table has one today. This is about the day somebody
        // writes "the deck's own theme" and the script silently stops parsing.
        assert_eq!(quote("the deck's theme"), r"'the deck\'s theme'");
        assert_eq!(quote(r"a\backslash"), r"'a\\backslash'");
    }

    #[test]
    fn the_script_says_it_is_generated_and_where_from() {
        // Somebody will find this file in their config directory a year later
        // and want to know whether editing it is pointless.
        let text = script();

        assert!(text.contains("Generated by `slidx completions fish`"), "{text}");
        assert!(text.contains("Do not edit by hand"), "{text}");
    }
}
