//! Nushell completions.
//!
//! Nushell completes an external command from an `extern` declaration — a typed
//! signature for a program it does not own. That is the closest fit of any shell
//! to what [`crate::command`] already holds, because the table is a typed
//! signature too: every flag knows whether it takes a value and what to call it.
//!
//! One `extern` per command, its flags with their summaries as comments, and the
//! command's own summary on the line above — which is what Nushell shows in the
//! menu.
//!
//! ## Three things left out on purpose
//!
//! **`--help` is not declared.** Nushell adds a help flag to every signature it
//! is given, and declaring it a second time is a parse error — which would take
//! the whole file with it, not just that one command.
//!
//! **Every positional is optional, and a rest argument follows them.** A
//! signature that rejects a command line replaces slidx's own message about it
//! with Nushell's. `slidx completions` with no shell prints a list of shells and
//! where each script goes; declared as a required argument, Nushell would refuse
//! to run it at all and that message would never be reached.
//!
//! **A repeatable flag is declared once.** Nushell signatures cannot say that a
//! flag may be given twice. `--allow` and `--target` are the two, and the
//! generated file says so where somebody will read it.

use crate::command::{Command, Flag, ALL, ROOT};

/// The type Nushell should expect after a flag.
///
/// `string` and `int` only. Nushell has richer shapes — `path` completes files —
/// and this deliberately does not use them: the file cannot be run here to find
/// out which spellings this version of Nushell accepts, and a signature that
/// fails to parse takes every command in the file down with it.
fn shape(flag: &Flag) -> &'static str {
    match flag.value {
        Some("<number>") => "int",
        _ => "string",
    }
}

/// Every positional in a usage line, as Nushell parameters.
///
/// Read out of `usage` rather than declared separately, so a command that grows
/// an argument grows one here. `[path]` and `<version>` both become optional,
/// for the reason in the module docs.
fn positionals(usage: &str) -> Vec<String> {
    usage
        .split_whitespace()
        .filter(|token| *token != "[options]")
        .filter_map(|token| {
            let name = token.trim_matches(['[', ']', '<', '>']);

            (token.starts_with(['[', '<']) && !name.is_empty()).then(|| format!("{name}?: string"))
        })
        .collect()
}

pub fn script() -> String {
    let mut out = String::from(
        "# slidx completions for Nushell.\n\
         #\n\
         # Generated by `slidx completions nushell` from the same table the parser\n\
         # reads, so what completes is what runs. Do not edit by hand.\n\
         #\n\
         #     slidx completions nushell | save --force ~/.config/nushell/slidx.nu\n\
         #\n\
         # then, in config.nu:\n\
         #\n\
         #     source ~/.config/nushell/slidx.nu\n\
         #\n\
         # --help is left out of every signature: Nushell adds one to a command it\n\
         # knows the shape of, and declaring it twice is a parse error that would\n\
         # take this whole file with it.\n\
         #\n\
         # A flag slidx accepts more than once — `--allow`, `--target` — is declared\n\
         # once, because a Nushell signature cannot say otherwise. Reach the binary\n\
         # directly to repeat one: `^slidx lint --allow a --allow b`.\n\n",
    );

    let root: Vec<&'static Flag> = ROOT.iter().collect();
    out.push_str(&extern_for("slidx", "the whole life of a talk", &[], &root, &[]));

    for entry in ALL {
        out.push('\n');
        out.push_str(&command(entry));
    }

    out
}

/// One command, and its children where it has them.
fn command(entry: &'static Command) -> String {
    let mut out = extern_for(
        &format!("slidx {}", entry.name),
        entry.summary,
        &positionals(entry.usage),
        &entry.all_flags(),
        entry.subcommands,
    );

    for child in entry.subcommands {
        out.push('\n');
        out.push_str(&extern_for(
            &format!("slidx {} {}", entry.name, child.name),
            child.summary,
            &positionals(child.usage),
            &child.all_flags(),
            &[],
        ));
    }

    out
}

/// One `extern` block.
///
/// A parent's children are offered as its first argument, which is what makes
/// `slidx version <tab>` list them. Nushell has no way to type that as a set, so
/// they go in the comment where its menu will show them.
fn extern_for(
    name: &str,
    summary: &str,
    positionals: &[String],
    flags: &[&'static Flag],
    subcommands: &'static [Command],
) -> String {
    let mut out = format!("# {summary}\nextern \"{name}\" [\n");

    for positional in positionals {
        out.push_str(&format!("  {positional}\n"));
    }

    if !subcommands.is_empty() {
        out.push_str(&format!(
            "  command?: string  # one of: {}\n",
            subcommands.iter().map(|child| child.name).collect::<Vec<_>>().join(", ")
        ));
    }

    let listed: Vec<&&Flag> = flags.iter().filter(|flag| !declared_by_nushell(flag)).collect();
    let width = listed.iter().map(|flag| parameter(flag).chars().count()).max().unwrap_or(0);

    for flag in listed {
        out.push_str(&format!(
            "  {:<width$}  # {}\n",
            parameter(flag),
            flag.summary,
            width = width
        ));
    }

    // Nothing declared can be refused, and slidx's own message about a bad
    // argument is better than Nushell's about a signature.
    out.push_str("  ...rest: string\n]\n");

    out
}

/// `--json`, `--theme: string`, or `--version(-V)`.
fn parameter(flag: &Flag) -> String {
    let short = match flag.short {
        Some(letter) => format!("({letter})", letter = format_args!("-{letter}")),
        None => String::new(),
    };

    match flag.value {
        Some(_) => format!("--{}{short}: {}", flag.long, shape(flag)),
        None => format!("--{}{short}", flag.long),
    }
}

/// Whether Nushell has already put this flag in the signature itself.
fn declared_by_nushell(flag: &Flag) -> bool {
    flag.long == "help"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command;

    #[test]
    fn every_command_gets_a_signature_nushell_can_complete_from() {
        let text = script();

        for entry in ALL {
            assert!(
                text.contains(&format!("extern \"slidx {}\" [", entry.name)),
                "{} has no extern",
                entry.name
            );
        }
    }

    #[test]
    fn a_nested_command_is_declared_under_its_parent_the_way_it_is_typed() {
        // `slidx version install` is one command name in Nushell, spaces and
        // all, so the extern has to be spelled the way somebody types it.
        assert!(script().contains("extern \"slidx version install\" ["), "{}", script());
    }

    #[test]
    fn a_parent_lists_its_children_where_the_menu_will_show_them() {
        // Nushell cannot type "one of these words", so the set goes in the
        // comment beside the argument.
        assert!(script().contains("one of: current, list, install, use, remove"), "{}", script());
    }

    #[test]
    fn a_flag_that_takes_a_value_is_typed_and_a_switch_is_not() {
        let text = script();

        assert!(text.contains("--theme: string"), "{text}");
        assert!(text.contains("--strict "), "{text}");
        assert!(!text.contains("--strict:"), "{text}");
    }

    #[test]
    fn a_flag_that_wants_a_number_is_typed_as_one() {
        // So `slidx preview --port banana` is refused by the shell before it
        // reaches a socket call.
        assert!(script().contains("--port: int"), "{}", script());
    }

    #[test]
    fn a_short_letter_is_written_the_way_nushell_spells_a_pair() {
        assert!(script().contains("--version(-V)"), "{}", script());
    }

    #[test]
    fn the_help_flag_is_left_to_nushell_and_the_file_says_why() {
        // Declaring it twice is a parse error, and a parse error in this file
        // costs every command in it rather than one.
        let text = script();

        assert!(!text.contains("--help(-h)"), "{text}");
        assert!(text.contains("Nushell adds one to a command it"), "{text}");
    }

    #[test]
    fn every_positional_is_optional_and_a_rest_argument_follows_it() {
        // A signature that refuses a command line replaces slidx's message
        // about it with Nushell's, and slidx's is the one that says what to do.
        let text = script();

        assert!(text.contains("path?: string"), "{text}");
        assert!(text.contains("shell?: string"), "{text}");
        assert!(!text.contains("path: string"), "{text}");

        assert_eq!(
            text.matches("...rest: string").count(),
            text.matches("extern \"").count(),
            "an extern without a rest argument can refuse a valid command line"
        );
    }

    #[test]
    fn a_positional_is_read_out_of_the_usage_line_rather_than_declared_twice() {
        assert_eq!(positionals("lint [path] [options]"), ["path?: string"]);
        assert_eq!(positionals("version use <version>"), ["version?: string"]);
        assert!(positionals("doctor [options]").is_empty());
    }

    #[test]
    fn the_root_command_carries_the_flags_that_come_before_a_subcommand() {
        let text = script();

        assert!(text.contains("extern \"slidx\" ["), "{text}");
        // A switch, so nothing follows it — `--version` takes no value.
        assert!(text.contains("--version(-V)  #"), "{text}");
    }

    #[test]
    fn a_summary_is_the_line_above_the_signature_because_that_is_what_nushell_shows() {
        for entry in command::ALL {
            assert!(
                script().contains(&format!("# {}\nextern \"slidx {}\"", entry.summary, entry.name)),
                "{} has no description above its extern",
                entry.name
            );
        }
    }

    #[test]
    fn a_comment_carries_no_newline_out_of_a_summary() {
        // Every summary is a `#` comment. A newline inside one would make the
        // rest of it a line of Nushell.
        for line in script().lines() {
            if let Some(comment) = line.split_once('#') {
                assert!(!comment.1.contains('\n'));
            }
        }
    }

    #[test]
    fn the_script_says_it_is_generated_and_where_from() {
        let text = script();

        assert!(text.contains("Generated by `slidx completions nushell`"), "{text}");
        assert!(text.contains("Do not edit by hand"), "{text}");
    }
}
