//! PowerShell completions.
//!
//! `Register-ArgumentCompleter -Native` hands the completer the whole command
//! line as text and expects a list of `CompletionResult` objects back. There is
//! no tree to declare, so the script carries the same one bash does — work out
//! which command and subcommand are already on the line, then emit the
//! candidates that follow.
//!
//! PowerShell shows a tooltip for each candidate, so everything carries its
//! summary. The list is filtered by what has been typed, which the completer
//! does itself rather than leaving to the shell.

use crate::command::{Command, Flag, ALL, ROOT};

/// A PowerShell single-quoted string: only `'` is special, doubled to escape.
///
/// Single quotes rather than double, because a double-quoted string in
/// PowerShell interpolates `$` — and a summary mentioning `$PROFILE` or a
/// variable would otherwise be expanded when the script loads.
fn quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', "''"))
}

/// One candidate: what to insert, what to list it as, and its tooltip.
fn result(value: &str, summary: &str) -> String {
    format!(
        "[CompletionResult]::new({}, {}, [CompletionResultType]::ParameterValue, {})",
        quote(value),
        quote(value),
        quote(summary)
    )
}

fn parameter(flag: &Flag, summary: &str) -> String {
    let long = format!("--{}", flag.long);

    format!(
        "[CompletionResult]::new({}, {}, [CompletionResultType]::ParameterName, {})",
        quote(&long),
        quote(&long),
        quote(summary)
    )
}

pub fn script() -> String {
    let mut out = String::from(
        "# slidx completions for PowerShell.\n\
         #\n\
         # Generated by `slidx completions powershell` from the same table the\n\
         # parser reads, so what completes is what runs. Do not edit by hand.\n\n\
         using namespace System.Management.Automation\n\
         using namespace System.Management.Automation.Language\n\n\
         Register-ArgumentCompleter -Native -CommandName slidx -ScriptBlock {\n\
         \x20   param($wordToComplete, $commandAst, $cursorPosition)\n\n\
         \x20   # The first two words that are not flags: the command, and its\n\
         \x20   # subcommand where it has one.\n\
         \x20   $words = $commandAst.CommandElements | Select-Object -Skip 1 |\n\
         \x20       ForEach-Object { $_.ToString() } | Where-Object { -not $_.StartsWith('-') }\n\
         \x20   $command = if ($words.Count -ge 1) { $words[0] } else { '' }\n\
         \x20   $sub = if ($words.Count -ge 2) { $words[1] } else { '' }\n\n\
         \x20   $candidates = @()\n\n",
    );

    out.push_str("    if ($command -eq '') {\n        $candidates = @(\n");
    for entry in ALL {
        out.push_str(&format!("            {}\n", result(entry.name, entry.summary)));
    }
    for flag in ROOT {
        out.push_str(&format!("            {}\n", parameter(flag, flag.summary)));
    }
    out.push_str("        )\n    }\n");

    for entry in ALL {
        out.push_str(&arm(entry));
    }

    out.push_str(
        "\n    $candidates | Where-Object { $_.CompletionText -like \"$wordToComplete*\" }\n\
         }\n",
    );

    out
}

fn arm(entry: &'static Command) -> String {
    if !entry.has_subcommands() {
        return format!(
            "    elseif ($command -eq '{}' ) {{\n        $candidates = @(\n{}        )\n    }}\n",
            entry.name,
            flags(entry.all_flags(), 12)
        );
    }

    let mut out = format!("    elseif ($command -eq '{}' ) {{\n", entry.name);

    for child in entry.subcommands {
        out.push_str(&format!(
            "        if ($sub -eq '{}') {{\n            $candidates = @(\n{}            )\n        }}\n        else",
            child.name,
            flags(child.all_flags(), 16)
        ));
    }

    // No subcommand chosen yet: offer the children and the parent's flags.
    out.push_str(" {\n            $candidates = @(\n");
    for child in entry.subcommands {
        out.push_str(&format!("                {}\n", result(child.name, child.summary)));
    }
    for flag in entry.all_flags() {
        out.push_str(&format!("                {}\n", parameter(flag, flag.summary)));
    }
    out.push_str("            )\n        }\n    }\n");

    out
}

fn flags(flags: Vec<&'static Flag>, indent: usize) -> String {
    let pad = " ".repeat(indent);

    flags.iter().map(|flag| format!("{pad}{}\n", parameter(flag, flag.summary))).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_script_registers_a_native_completer_for_the_binary() {
        assert!(script().contains("Register-ArgumentCompleter -Native -CommandName slidx"));
    }

    #[test]
    fn every_command_is_offered_with_a_tooltip() {
        let text = script();

        assert!(text.contains("'doctor'"), "{text}");
        assert!(text.contains("'check this machine before you speak'"), "{text}");
    }

    #[test]
    fn a_flag_is_offered_as_a_parameter_rather_than_as_a_value() {
        // PowerShell styles and sorts the two differently, and a flag listed
        // as a value reads as something to type literally.
        assert!(
            script().contains("'--json', '--json', [CompletionResultType]::ParameterName"),
            "{}",
            script()
        );
    }

    #[test]
    fn a_nested_command_is_offered_once_its_parent_is_on_the_line() {
        let text = script();

        assert!(text.contains("$command -eq 'version'"), "{text}");
        assert!(text.contains("$sub -eq 'install'"), "{text}");
    }

    #[test]
    fn flags_are_skipped_when_working_out_which_command_is_on_the_line() {
        // `slidx version --json <tab>` still has to know it is inside
        // `version`, or the completer falls back to offering commands.
        assert!(script().contains("Where-Object { -not $_.StartsWith('-') }"));
    }

    #[test]
    fn candidates_are_filtered_by_what_has_been_typed() {
        assert!(script().contains("$_.CompletionText -like \"$wordToComplete*\""));
    }

    #[test]
    fn a_description_is_single_quoted_so_a_dollar_sign_is_not_expanded() {
        // A double-quoted PowerShell string interpolates. A summary mentioning
        // $PROFILE would otherwise be replaced when the script loads.
        assert_eq!(quote("put it in $PROFILE"), "'put it in $PROFILE'");
    }

    #[test]
    fn a_quote_in_a_description_is_doubled_rather_than_ending_the_string() {
        assert_eq!(quote("the deck's theme"), "'the deck''s theme'");
    }

    #[test]
    fn the_namespaces_the_completion_types_live_in_are_imported() {
        // Without these the CompletionResult constructor is not in scope and
        // the script fails at load with a type-not-found error.
        let text = script();

        assert!(text.contains("using namespace System.Management.Automation"), "{text}");
        assert!(text.contains("using namespace System.Management.Automation.Language"), "{text}");
    }

    #[test]
    fn every_brace_is_closed() {
        let text = script();

        assert_eq!(text.matches('{').count(), text.matches('}').count());
    }

    #[test]
    fn the_script_says_it_is_generated_and_where_from() {
        let text = script();

        assert!(text.contains("Generated by `slidx completions powershell`"), "{text}");
        assert!(text.contains("Do not edit by hand"), "{text}");
    }
}
