//! ush completions, in the only shape ush can take them.
//!
//! ush completes a known tool from a catalogue compiled into ush itself —
//! `crates/ush_shell/src/repl/contextual/tool_catalog/`, where `CARGO_COMMANDS`
//! and `PNPM_COMMANDS` live. There is no file a third-party binary can install
//! and no protocol it can speak, so slidx cannot make ush complete `slidx` from
//! this repository. That is a fact about where the list lives, not a gap in
//! either tool.
//!
//! What slidx can do is write the catalogue entry, in ush's own shape, generated
//! from the same table everything else reads — so adopting it upstream is a copy
//! rather than a transcription, and regenerating it after a command is added is
//! one command rather than an afternoon of diffing.
//!
//! It is Rust, not a shell script, and it goes in ush's tree rather than
//! anybody's config directory. The generated header says so, because somebody
//! will otherwise try to source it.

use crate::command::{Flag, ALL, ROOT};

/// A `&[&str]` in ush's layout: one entry per line, trailing comma.
fn list(name: &str, items: impl Iterator<Item = String>) -> String {
    let entries: String = items.map(|item| format!("    \"{item}\",\n")).collect();

    format!("pub(crate) const {name}: &[&str] = &[\n{entries}];\n")
}

/// Every flag any command accepts, deduped, in table order.
///
/// ush keeps one flat option list per tool rather than one per subcommand, so
/// this is a union. The alternative — offering only the current subcommand's
/// flags — is not expressible in the shape ush's catalogue has.
fn flags() -> Vec<&'static Flag> {
    let mut seen: Vec<&'static Flag> = Vec::new();

    for flag in ROOT.iter().chain(ALL.iter().flat_map(|entry| {
        entry.flags.iter().chain(entry.subcommands.iter().flat_map(|child| child.flags.iter()))
    })) {
        if !seen.iter().any(|kept| kept.long == flag.long) {
            seen.push(flag);
        }
    }

    seen
}

/// One `option_spec` per kind of value, which is how ush groups them.
///
/// `path_value` is what makes ush offer a filename after the flag, and it comes
/// straight from the placeholder the table already declares: `<path>` is a path
/// and `<name>` is not.
fn specs() -> String {
    let of = |wants_a_path: bool| -> String {
        flags()
            .iter()
            .filter(|flag| flag.takes_value())
            .filter(|flag| (flag.value == Some("<path>")) == wants_a_path)
            .map(|flag| format!("\"--{}\"", flag.long))
            .collect::<Vec<_>>()
            .join(", ")
    };

    format!(
        "pub(crate) const SLIDX_OPTION_SPECS: &[OptionSpec] = &[\n\
         \x20   option_spec(&[{}], 1, true, false),\n\
         \x20   option_spec(&[{}], 1, false, false),\n\
         ];\n",
        of(true),
        of(false)
    )
}

pub fn script() -> String {
    let mut out = String::from(
        "// slidx completions for ush.\n\
         //\n\
         // ush completes a known tool from a catalogue compiled into itself, so there\n\
         // is no script slidx can ship and nothing here to source. This is that\n\
         // catalogue entry instead, generated by `slidx completions ush` from the same\n\
         // table the parser reads. Do not edit by hand — regenerate it.\n\
         //\n\
         // Adopting it is four edits in ush's own tree, and they are its maintainer's\n\
         // to make:\n\
         //\n\
         //   1. save this as crates/ush_shell/src/repl/contextual/tool_catalog/\n\
         //      slidx_tools.rs, and add `mod slidx_tools;` plus a re-export of these\n\
         //      three constants to tool_catalog.rs\n\
         //   2. descriptions.rs: SLIDX_COMMAND = \"slidx command\", and one per nested\n\
         //      group below\n\
         //   3. tools.rs: a `complete_slidx` shaped like `complete_go` — it dispatches\n\
         //      on the first positional, which is what a nested list is for\n\
         //   4. complete.rs: \"slidx\" => complete_slidx(args, word)\n\
         //\n\
         // Then run `cargo fmt` on it. This writes ush's spelling — its imports, its\n\
         // visibility, its constructors — and not its line breaks, which belong to\n\
         // whatever rustfmt ush is pinned to rather than to slidx.\n\n\
         use super::super::options::{OptionSpec, option_spec};\n\n",
    );

    out.push_str(&list("SLIDX_COMMANDS", ALL.iter().map(|entry| entry.name.to_string())));
    out.push('\n');

    for entry in ALL.iter().filter(|entry| entry.has_subcommands()) {
        out.push_str(&list(
            &format!("SLIDX_{}_COMMANDS", entry.name.to_uppercase().replace('-', "_")),
            entry.subcommands.iter().map(|child| child.name.to_string()),
        ));
        out.push('\n');
    }

    out.push_str(&list("SLIDX_OPTIONS", flags().iter().map(|flag| format!("--{}", flag.long))));
    out.push('\n');
    out.push_str(&specs());

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command;

    #[test]
    fn every_command_is_in_the_catalogue() {
        let text = script();

        for entry in ALL {
            assert!(text.contains(&format!("\"{}\",", entry.name)), "{} is missing", entry.name);
        }
    }

    #[test]
    fn a_command_with_children_gets_the_second_list_ush_dispatches_on() {
        // `complete_go` reads GO_MOD_COMMANDS off the first positional. This is
        // the same shape, so wiring it up is the same function.
        let text = script();

        assert!(text.contains("SLIDX_VERSION_COMMANDS: &[&str] = &["), "{text}");
        assert!(text.contains("\"install\","), "{text}");
    }

    #[test]
    fn every_flag_the_parser_accepts_is_offered() {
        let text = script();

        for entry in command::ALL {
            for flag in entry.all_flags() {
                assert!(
                    text.contains(&format!("\"--{}\",", flag.long)),
                    "--{} is missing",
                    flag.long
                );
            }
        }
    }

    #[test]
    fn a_flag_is_offered_once_however_many_commands_accept_it() {
        // `--json` is on five commands and ush's catalogue is flat. Five
        // identical entries would show up five times in its menu.
        let text = script();

        assert_eq!(text.matches("\"--json\",").count(), 1, "{text}");
    }

    #[test]
    fn a_flag_that_wants_a_path_is_marked_so_ush_offers_a_filename() {
        // The one thing an option spec is for. `--dir` takes a path and
        // `--theme` takes a theme name, and the difference is already in the
        // table's placeholder.
        let text = script();
        let path_spec = text
            .lines()
            .find(|line| line.contains("1, true, false"))
            .expect("a spec for path-valued flags");

        assert!(path_spec.contains("\"--dir\""), "{path_spec}");
        assert!(!path_spec.contains("\"--theme\""), "{path_spec}");
    }

    #[test]
    fn a_switch_is_in_no_option_spec_because_nothing_follows_it() {
        // An `option_spec` says how many arguments a flag eats. Listing a
        // switch there would make ush swallow the next word.
        for line in script().lines().filter(|line| line.contains("option_spec(")) {
            assert!(!line.contains("\"--strict\""), "{line}");
            assert!(!line.contains("\"--json\""), "{line}");
        }
    }

    #[test]
    fn it_is_written_in_ushs_own_spelling_so_it_compiles_where_it_lands() {
        // Same import, same visibility, same constructor. A file that needed
        // editing before it built would be a transcription again.
        let text = script();

        assert!(text.contains("use super::super::options::{OptionSpec, option_spec};"), "{text}");
        assert!(text.contains("pub(crate) const SLIDX_COMMANDS"), "{text}");
        assert!(!text.contains("pub const"), "{text}");
    }

    #[test]
    fn it_says_it_is_not_a_script_and_where_it_actually_goes() {
        // Somebody will otherwise try to source a Rust file, and the error they
        // get will not explain any of this.
        let text = script();

        assert!(text.contains("no script slidx can ship"), "{text}");
        assert!(text.contains("tool_catalog"), "{text}");
        assert!(text.contains("Generated by") || text.contains("generated by"), "{text}");
    }

    #[test]
    fn nothing_slidx_declines_to_do_is_offered_as_a_command() {
        // ush's menu is the place somebody would read `build` as a promise.
        let commands = script()
            .split("SLIDX_OPTIONS")
            .next()
            .expect("the command lists come first")
            .to_string();

        for (declined, _) in command::DECLINED {
            assert!(!commands.contains(&format!("\"{declined}\",")), "{declined} is offered");
        }
    }
}
