//! zsh completions.
//!
//! zsh's `_arguments` understands a command tree natively, which makes this the
//! shell where the generated script is most nearly a transcription of the
//! table: one `_describe` per level of commands, one `_arguments` spec per
//! command, and a `case` to pick which.
//!
//! Descriptions are shown in zsh's menu, so everything carries its summary.

use crate::command::{Command, Flag, ALL, ROOT};

/// Single quotes. Inside them zsh treats everything literally, and the only
/// way to get a `'` is to close, escape one, and reopen — which is what this
/// does rather than reaching for double quotes, where `$` and backtick would
/// then have to be handled too.
fn quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

/// A `_describe` entry: `name:description`, with the colon in a description
/// escaped so it does not read as a second separator.
fn described(name: &str, summary: &str) -> String {
    quote(&format!("{name}:{}", summary.replace(':', r"\:")))
}

pub fn script() -> String {
    let mut out = String::from(
        "#compdef slidx\n\
         #\n\
         # slidx completions for zsh.\n\
         #\n\
         # Generated by `slidx completions zsh` from the same table the parser\n\
         # reads, so what completes is what runs. Do not edit by hand.\n\n\
         _slidx() {\n\
         \x20   local context state state_descr line\n\
         \x20   typeset -A opt_args\n\n\
         \x20   _arguments -C \\\n",
    );

    for flag in ROOT {
        out.push_str(&format!("        {} \\\n", spec(flag)));
    }

    out.push_str(
        "        '1: :->command' \\\n\
         \x20       '*:: :->rest'\n\n\
         \x20   case $state in\n\
         \x20       command)\n\
         \x20           _describe -t commands 'slidx command' _slidx_commands\n\
         \x20           ;;\n\
         \x20       rest)\n\
         \x20           case $words[1] in\n",
    );

    for entry in ALL {
        out.push_str(&arm(entry));
    }

    out.push_str(
        "            esac\n\
         \x20           ;;\n\
         \x20   esac\n\
         }\n\n",
    );

    out.push_str(&format!(
        "_slidx_commands=(\n{}\n)\n\n",
        ALL.iter()
            .map(|entry| format!("    {}", described(entry.name, entry.summary)))
            .collect::<Vec<_>>()
            .join("\n")
    ));

    for entry in ALL.iter().filter(|entry| entry.has_subcommands()) {
        out.push_str(&format!(
            "_slidx_{}_commands=(\n{}\n)\n\n",
            entry.name,
            entry
                .subcommands
                .iter()
                .map(|child| format!("    {}", described(child.name, child.summary)))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }

    out.push_str("_slidx \"$@\"\n");
    out
}

/// One arm of the `case` over the first word.
fn arm(entry: &'static Command) -> String {
    if !entry.has_subcommands() {
        return format!(
            "                {})\n\
             \x20                   _arguments \\\n{}\n\
             \x20                   ;;\n",
            entry.name,
            specs(entry.all_flags(), 24)
        );
    }

    format!(
        "                {name})\n\
         \x20                   _arguments -C \\\n\
         \x20                       '1: :->subcommand' \\\n\
         \x20                       '*:: :->subrest'\n\
         \x20                   case $state in\n\
         \x20                       subcommand)\n\
         \x20                           _describe -t commands 'slidx {name} command' _slidx_{name}_commands\n\
         \x20                           ;;\n\
         \x20                       subrest)\n\
         \x20                           case $words[1] in\n{arms}\
         \x20                           esac\n\
         \x20                           ;;\n\
         \x20                   esac\n\
         \x20                   ;;\n",
        name = entry.name,
        arms = entry
            .subcommands
            .iter()
            .map(|child| format!(
                "                                {})\n\
                 \x20                                   _arguments \\\n{}\n\
                 \x20                                   ;;\n",
                child.name,
                specs(child.all_flags(), 36)
            ))
            .collect::<String>()
    )
}

fn specs(flags: Vec<&'static Flag>, indent: usize) -> String {
    let pad = " ".repeat(indent);

    flags.iter().map(|flag| format!("{pad}{}", spec(flag))).collect::<Vec<_>>().join(" \\\n")
}

/// One `_arguments` spec.
///
/// `(-h --help)` marks the pair as mutually exclusive, so zsh stops offering
/// the other spelling once one is typed. `=` after the long name is what tells
/// zsh the flag takes a value, and `:name:` names it in the menu.
fn spec(flag: &Flag) -> String {
    let long = format!("--{}", flag.long);
    let value = flag
        .value
        .map(|placeholder| format!(":{}:", placeholder.trim_matches(['<', '>'])))
        .unwrap_or_default();

    match flag.short {
        Some(letter) => {
            quote(&format!("(-{letter} {long})'{{-{letter},{long}}}'[{}]{value}", flag.summary))
        }
        None => quote(&format!("{long}[{}]{value}", flag.summary)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_script_declares_itself_a_completion_for_slidx() {
        // Without the tag on the first line zsh never loads it, however
        // correctly it is placed on the fpath.
        assert!(script().starts_with("#compdef slidx\n"));
    }

    #[test]
    fn every_command_is_offered_with_its_summary() {
        let text = script();

        assert!(text.contains("_slidx_commands=("), "{text}");
        assert!(text.contains("'doctor:check this machine before you speak'"), "{text}");
    }

    #[test]
    fn a_command_with_children_gets_its_own_list() {
        assert!(script().contains("_slidx_version_commands=("), "{}", script());
    }

    #[test]
    fn a_flag_that_takes_a_value_names_what_it_wants() {
        // The placeholder is what zsh shows in the menu, so `--theme <name>`
        // reads as asking for a name rather than for nothing in particular.
        assert!(
            script().contains("--theme[Theme to resolve colours against]:name:"),
            "{}",
            script()
        );
    }

    #[test]
    fn a_switch_asks_for_no_value() {
        let text = script();

        assert!(text.contains("--json[Print the diagnostics as JSON]'"), "{text}");
    }

    #[test]
    fn a_short_and_long_pair_is_marked_mutually_exclusive() {
        // So zsh stops offering `--help` once `-h` is typed, and the menu does
        // not list two ways to say the same thing.
        assert!(script().contains("(-h --help)"), "{}", script());
    }

    #[test]
    fn a_colon_in_a_description_is_escaped_so_it_does_not_read_as_a_separator() {
        // zsh splits a _describe entry on the first colon. An unescaped one in
        // a summary silently truncates the description at that point.
        assert_eq!(described("x", "a: b"), r"'x:a\: b'");
    }

    #[test]
    fn a_quote_in_a_description_is_escaped_rather_than_ending_the_string() {
        assert_eq!(quote("the deck's theme"), r"'the deck'\''s theme'");
    }

    #[test]
    fn every_case_is_closed() {
        // An unbalanced `case` is a syntax error, and this file is loaded at
        // every shell start once it is installed.
        let text = script();

        assert_eq!(text.matches("case $").count(), text.matches("esac").count());
    }

    #[test]
    fn the_script_says_it_is_generated_and_where_from() {
        let text = script();

        assert!(text.contains("Generated by `slidx completions zsh`"), "{text}");
        assert!(text.contains("Do not edit by hand"), "{text}");
    }
}
